#!/usr/bin/env python3
"""
Generate Python WebDriver BiDi command modules from CDDL specification.

This generator reads CDDL (Concise Data Definition Language) specification files
and produces Python type definitions and command classes that conform to the
WebDriver BiDi protocol.

Usage:
    python generate_bidi.py <cddl_file> <output_dir> <spec_version>

Example:
    python generate_bidi.py local.cddl ./selenium/webdriver/common/bidi 1.0
"""

import argparse
import importlib.util
import logging
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from textwrap import dedent, indent as tw_indent
from typing import Any, Dict, List, Optional, Set, Tuple

__version__ = "1.0.0"

# Logging setup
log_level = logging.INFO
logging.basicConfig(level=log_level)
logger = logging.getLogger("generate_bidi")

# File headers
SHARED_HEADER = """# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules."""

MODULE_HEADER = f"""{SHARED_HEADER}
#
# WebDriver BiDi module: {{}}
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from .common import command_builder
"""


def indent(s: str, n: int) -> str:
    """Indent a string by n spaces."""
    return tw_indent(s, n * " ")


def load_enhancements_manifest(manifest_path: Optional[str]) -> Dict[str, Any]:
    """Load enhancement manifest from a Python file.

    Args:
        manifest_path: Path to Python file containing ENHANCEMENTS dict

    Returns:
        Dictionary with enhancement rules, or empty dict if no manifest provided
    """
    if not manifest_path:
        return {}

    manifest_file = Path(manifest_path)
    if not manifest_file.exists():
        logger.warning(f"Enhancement manifest not found: {manifest_path}")
        return {}

    try:
        spec = importlib.util.spec_from_file_location(
            "bidi_enhancements", manifest_file
        )
        if spec is None or spec.loader is None:
            logger.warning(f"Could not load manifest: {manifest_path}")
            return {}

        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        enhancements = getattr(module, "ENHANCEMENTS", {})
        dataclass_methods = getattr(module, "DATACLASS_METHOD_TEMPLATES", {})
        method_docstrings = getattr(module, "DATACLASS_METHOD_DOCSTRINGS", {})

        logger.info(f"Loaded enhancement manifest from: {manifest_path}")
        logger.debug(f"Enhancements for modules: {list(enhancements.keys())}")

        return {
            "enhancements": enhancements,
            "dataclass_methods": dataclass_methods,
            "method_docstrings": method_docstrings,
        }
    except Exception as e:
        logger.error(f"Failed to load enhancement manifest: {e}", exc_info=True)
        return {}


class CddlType(Enum):
    """CDDL type mappings to Python types."""

    TSTR = "str"  # text string
    TEXT = "str"  # text (alias)
    UINT = "int"  # unsigned integer
    INT = "int"  # signed integer
    NINT = "int"  # negative integer
    BOOL = "bool"  # boolean
    NULL = "None"  # null
    ANY = "Any"  # any type

    @classmethod
    def get_annotation(cls, cddl_type: str) -> str:
        """Get Python type annotation for a CDDL type."""
        cddl_type = cddl_type.strip().lower()

        # Handle basic types
        for member in cls:
            if cddl_type == member.name.lower():
                return member.value

        # Handle composite types
        if cddl_type.startswith("["):  # Array
            inner = cddl_type.strip("[]+ ")
            inner_type = cls.get_annotation(inner)
            return f"List[{inner_type}]"

        if cddl_type.startswith("{"):  # Map/Dict
            return "Dict[str, Any]"

        # Default to Any for unknown types
        return "Any"


@dataclass
class CddlCommand:
    """Represents a CDDL command definition."""

    module: str
    name: str
    params: Dict[str, str] = field(default_factory=dict)
    result: Optional[str] = None
    description: str = ""

    def to_python_method(self, enhancements: Optional[Dict[str, Any]] = None) -> str:
        """Generate Python method code for this command.

        Args:
            enhancements: Dictionary with enhancement rules for this method
        """
        enhancements = enhancements or {}
        method_name = self._camel_to_snake(self.name)

        # Build parameter list with type hints
        param_strs = []
        param_names = []  # Keep track of parameter names for later use
        for param_name, param_type in self.params.items():
            python_type = CddlType.get_annotation(param_type)
            snake_param = self._camel_to_snake(param_name)
            param_names.append((param_name, snake_param))
            param_strs.append(f"{snake_param}: {python_type} = None")

        if param_strs:
            param_list = "self, " + ", ".join(param_strs)
        else:
            param_list = "self"

        # Build method body
        body = f"    def {method_name}({param_list}):\n"
        body += f'        """{self.description or "Execute " + self.module + "." + self.name}."""\n'

        # Add validation if specified
        if "validate" in enhancements:
            validate_func = enhancements["validate"]
            # Build parameter list for validation function
            param_args = ", ".join(f"{snake}={snake}" for _, snake in param_names)
            body += f"        {validate_func}({param_args})\n"
            body += "\n"

        # Add transformation and preprocessing
        # First, check if any transform is needed
        if "transform" in enhancements:
            transform_func = enhancements["transform"]
            # For download_behavior, we need special handling
            # Find the parameters that are input to the transform
            if self.name == "setDownloadBehavior":
                body += "        download_behavior = None\n"
                body += f"        download_behavior = {transform_func}(allowed, destination_folder)\n"
                body += "\n"

        # Add preprocessing for serialization (check for to_bidi_dict method)
        if "preprocess" in enhancements:
            preprocess_rules = enhancements["preprocess"]
            for param_name, preprocess_type in preprocess_rules.items():
                snake_param = self._camel_to_snake(param_name)
                if preprocess_type == "check_serialize_method":
                    body += f"        if {snake_param} and hasattr({snake_param}, 'to_bidi_dict'):\n"
                    body += (
                        f"            {snake_param} = {snake_param}.to_bidi_dict()\n"
                    )
                    body += "\n"

        # Build params dict
        body += "        params = {\n"

        # For methods with transform, use the transformed value
        if "transform" in enhancements and self.name == "setDownloadBehavior":
            body += '            "downloadBehavior": download_behavior,\n'
            # Add other non-transformed parameters
            for param_name, snake_param in param_names:
                if param_name not in ["allowed", "destinationFolder"]:
                    body += f'            "{param_name}": {snake_param},\n'
        else:
            # Standard parameter mapping
            for param_name, snake_param in param_names:
                body += f'            "{param_name}": {snake_param},\n'

        body += "        }\n"
        body += "        params = {k: v for k, v in params.items() if v is not None}\n"
        body += f'        cmd = command_builder("{self.module}.{self.name}", params)\n'
        body += "        result = self._driver.execute(cmd)\n"

        # Add response handling for extraction/deserialization
        if "extract_field" in enhancements:
            extract_field = enhancements["extract_field"]
            extract_property = enhancements.get("extract_property")

            if extract_property:
                # Extract property from list items
                body += f'        if result and "{extract_field}" in result:\n'
                body += f'            items = result.get("{extract_field}", [])\n'
                body += f"            return [\n"
                body += f'                item.get("{extract_property}")\n'
                body += f"                for item in items\n"
                body += f"                if isinstance(item, dict)\n"
                body += f"            ]\n"
                body += f"        return []\n"
            else:
                # Simple field extraction
                body += f'        return result.get("{extract_field}") if result and "{extract_field}" in result else result\n'
        elif "deserialize" in enhancements:
            # Deserialize response to typed objects
            deserialize_rules = enhancements["deserialize"]
            for response_field, type_name in deserialize_rules.items():
                body += f'        if result and "{response_field}" in result:\n'
                body += f'            items = result.get("{response_field}", [])\n'
                body += f"            return [\n"
                body += f"                {type_name}(\n"
                body += self._generate_field_args(response_field, type_name) + "\n"
                body += f"                )\n"
                body += f"                if isinstance(item, dict)\n"
                body += f"                else item\n"
                body += f"                for item in items\n"
                body += f"            ]\n"
                body += f"        return []\n"
        else:
            # No special response handling, just return the result
            body += "        return result\n"

        return body

    def _generate_field_args(self, response_field: str, type_name: str) -> str:
        """Generate constructor arguments for deserializing response objects.

        For now, this handles ClientWindowInfo specifically.
        Could be extended to be more generic.
        """
        if type_name == "ClientWindowInfo":
            return (
                '                    active=item.get("active"),\n'
                '                    client_window=item.get("clientWindow"),\n'
                '                    height=item.get("height"),\n'
                '                    state=item.get("state"),\n'
                '                    width=item.get("width"),\n'
                '                    x=item.get("x"),\n'
                '                    y=item.get("y"),'
            )
        # For other types, add arg for each field
        return "                )"

    @staticmethod
    def _camel_to_snake(name: str) -> str:
        """Convert camelCase to snake_case."""
        name = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
        return re.sub("([a-z0-9])([A-Z])", r"\1_\2", name).lower()


@dataclass
class CddlTypeDefinition:
    """Represents a CDDL type definition."""

    module: str
    name: str
    fields: Dict[str, str] = field(default_factory=dict)
    description: str = ""

    def to_python_dataclass(self, enhancements: Optional[Dict[str, Any]] = None) -> str:
        """Generate Python dataclass code for this type.

        Args:
            enhancements: Dictionary containing dataclass_methods and method_docstrings
        """
        enhancements = enhancements or {}
        dataclass_methods = enhancements.get("dataclass_methods", {})
        method_docstrings = enhancements.get("method_docstrings", {})

        # Generate class name from type name (keep it as-is, don't split on underscores)
        class_name = self.name
        code = f"@dataclass\n"
        code += f"class {class_name}:\n"
        code += f'    """{self.description or self.name} type."""\n\n'

        if not self.fields:
            code += "    pass\n"
        else:
            for field_name, field_type in self.fields.items():
                # Convert CDDL type to Python type
                python_type = self._get_python_type(field_type)
                snake_name = CddlCommand._camel_to_snake(field_name)

                # Check if this field is a list type
                if "List[" in python_type:
                    code += f"    {snake_name}: {python_type} = field(default_factory=list)\n"
                else:
                    code += f"    {snake_name}: {python_type} = None\n"

            # Add custom methods if defined for this class
            if class_name in dataclass_methods:
                code += "\n"
                methods_dict = dataclass_methods[class_name]
                docstrings_dict = method_docstrings.get(class_name, {})

                for method_name in methods_dict:
                    method_impl = methods_dict[method_name]
                    docstring = docstrings_dict.get(method_name, "")
                    code += f"    def {method_name}(self):\n"
                    if docstring:
                        code += f'        """{docstring}"""\n'
                    code += f"        {method_impl}\n"
                    code += "\n"

        return code

    @staticmethod
    def _get_python_type(cddl_type: str) -> str:
        """Convert CDDL type to Python type annotation using Python 3.10+ syntax."""
        cddl_type = cddl_type.strip().lower()

        # Handle basic types
        type_mapping = {
            "tstr": "str",
            "text": "str",
            "uint": "int",
            "int": "int",
            "nint": "int",
            "bool": "bool",
            "null": "None",
        }

        for cddl, python in type_mapping.items():
            if cddl_type == cddl:
                # Use Python 3.10+ union syntax: type | None
                return f"{python} | None"

        # Handle arrays
        if cddl_type.startswith("["):
            inner = cddl_type.strip("[]+ ")
            inner_type = CddlTypeDefinition._get_python_type(inner)
            # Remove " | None" from inner type since it might be wrapped
            if " | None" in inner_type:
                inner_base = inner_type.replace(" | None", "")
                return f"list[{inner_base} | None] | None"
            return f"list[{inner_type}] | None"

        # Handle maps/dicts
        if cddl_type.startswith("{"):
            return "dict[str, Any] | None"

        # Default to Any for unknown/complex types
        return "Any | None"


@dataclass
class CddlModule:
    """Represents a CDDL module (e.g., script, network, browsing_context)."""

    name: str
    commands: List[CddlCommand] = field(default_factory=list)
    types: List[CddlTypeDefinition] = field(default_factory=list)

    def generate_code(self, enhancements: Optional[Dict[str, Any]] = None) -> str:
        """Generate Python code for this module.

        Args:
            enhancements: Dictionary with module-level enhancements
        """
        enhancements = enhancements or {}
        code = MODULE_HEADER.format(self.name)

        # Add imports if needed
        if self.types:
            code += "from dataclasses import field\n"
        if self.commands or self.types:
            code += "from typing import Generator\n"
            code += "from dataclasses import dataclass\n"

        code += "\n\n"

        # Generate type dataclasses first
        for type_def in self.types:
            code += type_def.to_python_dataclass(enhancements)
            code += "\n\n"

        # Generate class
        # Convert module name (camelCase or snake_case) to proper class name (PascalCase)
        class_name = module_name_to_class_name(self.name)
        code += f"class {class_name}:\n"
        code += f'    """WebDriver BiDi {self.name} module."""\n\n'
        code += "    def __init__(self, driver) -> None:\n"
        code += "        self._driver = driver\n\n"

        # Generate command methods
        if self.commands:
            for command in self.commands:
                # Get method-specific enhancements
                # Convert command name to snake_case to match enhancement manifest keys
                method_name_snake = command._camel_to_snake(command.name)
                method_enhancements = enhancements.get(method_name_snake, {})
                code += command.to_python_method(method_enhancements)
                code += "\n"
        else:
            code += "    pass\n"

        return code


class CddlParser:
    """Parse CDDL specification files."""

    def __init__(self, cddl_path: str):
        """Initialize parser with CDDL file path."""
        self.cddl_path = Path(cddl_path)
        self.content = ""
        self.modules: Dict[str, CddlModule] = {}
        self.definitions: Dict[str, str] = {}
        self._read_file()

    def _read_file(self) -> None:
        """Read and preprocess CDDL file."""
        if not self.cddl_path.exists():
            raise FileNotFoundError(f"CDDL file not found: {self.cddl_path}")

        with open(self.cddl_path, "r", encoding="utf-8") as f:
            self.content = f.read()

        logger.info(f"Loaded CDDL file: {self.cddl_path}")

    def parse(self) -> Dict[str, CddlModule]:
        """Parse CDDL content and return modules."""
        # Remove comments
        content = self._remove_comments(self.content)

        # Extract all definitions
        self._extract_definitions(content)

        # Extract type definitions by module
        self._extract_types()

        # Extract command definitions by module
        self._extract_commands()

        # If no modules found, create a default one from the filename
        if not self.modules:
            module_name = self.cddl_path.stem
            default_module = CddlModule(name=module_name)
            self.modules[module_name] = default_module
            logger.warning(f"No modules found in CDDL, creating default: {module_name}")

        return self.modules

    def _remove_comments(self, content: str) -> str:
        """Remove comments from CDDL content."""
        # CDDL uses ; for comments to end of line
        lines = content.split("\n")
        cleaned = []
        for line in lines:
            if ";" in line and not line.strip().startswith(";"):
                line = line[: line.index(";")]
            elif line.strip().startswith(";"):
                continue
            cleaned.append(line)
        return "\n".join(cleaned)

    def _extract_definitions(self, content: str) -> None:
        """Extract CDDL definitions (type definitions, commands, etc.)."""
        # Match pattern: Name = Definition
        # Handles multiline definitions properly
        pattern = r"(\w+(?:\.\w+)*)\s*=\s*(.+?)(?=\n\w+(?:\.\w+)?\s*=|\Z)"

        for match in re.finditer(pattern, content, re.DOTALL):
            name = match.group(1).strip()
            definition = match.group(2).strip()
            self.definitions[name] = definition
            logger.debug(f"Extracted definition: {name}")

    def _extract_types(self) -> None:
        """Extract type definitions from parsed definitions."""
        # Type definitions follow pattern: module.TypeName = { field: type, ... }
        # They have dots in the name and curly braces in the content
        # But they DON'T have method: "..." pattern (which means it's not a command)

        for def_name, def_content in self.definitions.items():
            # Skip if not a namespaced name (e.g., skip "EmptyParams", "Extensible")
            if "." not in def_name:
                continue

            # Skip if it's a command (contains method: pattern)
            if "method:" in def_content:
                continue

            # Skip if it's a union/choice (contains //)
            if "//" in def_content and not def_content.strip().startswith("{"):
                continue

            # Extract module.TypeName
            if "." in def_name:
                module_name, type_name = def_name.rsplit(".", 1)

                # Create module if not exists
                if module_name not in self.modules:
                    self.modules[module_name] = CddlModule(name=module_name)

                # Extract fields from type definition
                fields = self._extract_type_fields(def_content)

                if fields:  # Only create type if it has fields
                    type_def = CddlTypeDefinition(
                        module=module_name,
                        name=type_name,
                        fields=fields,
                        description=f"{type_name} type",
                    )
                    self.modules[module_name].types.append(type_def)
                    logger.debug(f"Found type: {def_name} with {len(fields)} fields")

    def _extract_type_fields(self, type_definition: str) -> Dict[str, str]:
        """Extract fields from a type definition block."""
        fields = {}

        # Remove outer braces
        clean_def = type_definition.strip()
        if clean_def.startswith("{"):
            clean_def = clean_def[1:]
        if clean_def.endswith("}"):
            clean_def = clean_def[:-1]

        # Parse each line for field: type patterns
        for line in clean_def.split("\n"):
            line = line.strip()
            if not line or "Extensible" in line or line.startswith("//"):
                continue

            # Match pattern: [?] fieldName: type
            match = re.match(r"\?\s*(\w+)\s*:\s*(.+?)(?:,\s*)?$", line)
            if not match:
                # Try without optional marker
                match = re.match(r"(\w+)\s*:\s*(.+?)(?:,\s*)?$", line)

            if match:
                field_name = match.group(1).strip()
                field_type = match.group(2).strip()

                # Skip lines that are part of nested definitions
                if "{" not in field_type and "(" not in field_type:
                    fields[field_name] = field_type
                    logger.debug(f"Extracted field {field_name}: {field_type}")

        return fields

    def _extract_commands(self) -> None:
        """Extract command definitions from parsed definitions."""
        # Find command definitions that follow pattern: module.Command = (method: "...", params: ...)
        command_pattern = re.compile(
            r"method:\s*['\"]([^'\"]+)['\"],\s*params:\s*(\w+(?:\.\w+)*)"
        )

        for def_name, def_content in self.definitions.items():
            matches = list(command_pattern.finditer(def_content))
            if matches:
                for match in matches:
                    method = match.group(1)  # e.g., "session.new"
                    params_type = match.group(2)  # e.g., "session.NewParameters"

                    # Extract module name from method
                    if "." in method:
                        module_name, command_name = method.split(".", 1)

                        # Create module if not exists
                        if module_name not in self.modules:
                            self.modules[module_name] = CddlModule(name=module_name)

                        # Extract parameters
                        params = self._extract_parameters(params_type)

                        # Create command
                        cmd = CddlCommand(
                            module=module_name,
                            name=command_name,
                            params=params,
                            description=f"Execute {method}",
                        )

                        self.modules[module_name].commands.append(cmd)
                        logger.debug(
                            f"Found command: {method} with params {params_type}"
                        )

    def _extract_parameters(self, params_type: str) -> Dict[str, str]:
        """Extract parameters from a parameter type definition."""
        params = {}

        if params_type not in self.definitions:
            logger.debug(f"Parameter type not found: {params_type}")
            return params

        definition = self.definitions[params_type]

        # Remove the outer curly braces and split by comma
        # Then parse each line for key: type patterns
        clean_def = definition.strip()
        if clean_def.startswith("{"):
            clean_def = clean_def[1:]
        if clean_def.endswith("}"):
            clean_def = clean_def[:-1]

        # Split by newlines and process each line
        for line in clean_def.split("\n"):
            line = line.strip()
            if not line or "Extensible" in line:
                continue

            # Match pattern: [?] name: type
            # Using a simple pattern that handles optional prefix
            match = re.match(r"\?\s*(\w+)\s*:\s*(.+?)(?:,\s*)?$", line)
            if not match:
                # Try without optional marker
                match = re.match(r"(\w+)\s*:\s*(.+?)(?:,\s*)?$", line)

            if match:
                param_name = match.group(1).strip()
                param_type = match.group(2).strip()

                # Skip lines that are part of nested definitions
                if "{" not in param_type and "(" not in param_type:
                    params[param_name] = param_type
                    logger.debug(
                        f"Extracted param {param_name}: {param_type} from {params_type}"
                    )

        return params


def module_name_to_class_name(module_name: str) -> str:
    """Convert module name to class name (PascalCase).

    Handles both camelCase (browsingContext) and snake_case (browsing_context).
    """
    if "_" in module_name:
        # Snake_case: browsing_context -> BrowsingContext
        return "".join(word.capitalize() for word in module_name.split("_"))
    else:
        # CamelCase: browsingContext -> BrowsingContext
        return module_name[0].upper() + module_name[1:] if module_name else ""


def module_name_to_filename(module_name: str) -> str:
    """Convert module name to Python filename (snake_case).

    Handles both camelCase (browsingContext) and snake_case (browsing_context).
    Special cases:
    - browsingContext -> browsing_context
    - webExtension -> webextension
    """
    # Handle explicit mappings for known camelCase names
    camel_to_snake_map = {
        "browsingContext": "browsing_context",
        "webExtension": "webextension",
    }

    if module_name in camel_to_snake_map:
        return camel_to_snake_map[module_name]

    if "_" in module_name:
        # Already snake_case
        return module_name
    else:
        # Convert camelCase to snake_case for other cases
        # This handles cases like "myModuleName" -> "my_module_name"
        import re

        s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", module_name)
        return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def generate_init_file(output_path: Path, modules: Dict[str, CddlModule]) -> None:
    """Generate __init__.py file for the module."""
    init_path = output_path / "__init__.py"

    code = f"""{SHARED_HEADER}

from __future__ import annotations

"""

    for module_name in sorted(modules.keys()):
        class_name = module_name_to_class_name(module_name)
        filename = module_name_to_filename(module_name)
        code += f"from .{filename} import {class_name}\n"

    code += f"\n__all__ = [\n"
    for module_name in sorted(modules.keys()):
        class_name = module_name_to_class_name(module_name)
        code += f'    "{class_name}",\n'
    code += "]\n"

    with open(init_path, "w", encoding="utf-8") as f:
        f.write(code)

    logger.info(f"Generated: {init_path}")


def main(
    cddl_file: str,
    output_dir: str,
    spec_version: str = "1.0",
    enhancements_manifest: Optional[str] = None,
) -> None:
    """Main entry point.

    Args:
        cddl_file: Path to CDDL specification file
        output_dir: Output directory for generated modules
        spec_version: BiDi spec version
        enhancements_manifest: Path to enhancement manifest Python file
    """
    output_path = Path(output_dir).resolve()
    output_path.mkdir(parents=True, exist_ok=True)

    logger.info(f"WebDriver BiDi Code Generator v{__version__}")
    logger.info(f"Input CDDL: {cddl_file}")
    logger.info(f"Output directory: {output_path}")
    logger.info(f"Spec version: {spec_version}")

    # Load enhancement manifest
    manifest = load_enhancements_manifest(enhancements_manifest)
    if manifest:
        logger.info(f"Loaded enhancement manifest from: {enhancements_manifest}")

    # Parse CDDL
    parser = CddlParser(cddl_file)
    modules = parser.parse()

    logger.info(f"Parsed {len(modules)} modules")

    # Clean up existing generated files
    for file_path in output_path.glob("*.py"):
        if file_path.name != "py.typed" and not file_path.name.startswith("_"):
            file_path.unlink()
            logger.debug(f"Removed: {file_path}")

    # Generate module files using snake_case filenames
    for module_name, module in sorted(modules.items()):
        filename = module_name_to_filename(module_name)
        module_path = output_path / f"{filename}.py"

        # Get module-specific enhancements (merge with dataclass templates)
        module_enhancements = manifest.get("enhancements", {}).get(module_name, {})

        # Add dataclass methods and docstrings to the enhancement data for this module
        full_module_enhancements = {
            **module_enhancements,
            "dataclass_methods": manifest.get("dataclass_methods", {}),
            "method_docstrings": manifest.get("method_docstrings", {}),
        }

        with open(module_path, "w", encoding="utf-8") as f:
            f.write(module.generate_code(full_module_enhancements))
        logger.info(f"Generated: {module_path}")

    # Generate __init__.py
    generate_init_file(output_path, modules)

    # Create py.typed marker
    py_typed_path = output_path / "py.typed"
    py_typed_path.touch()
    logger.info(f"Generated type marker: {py_typed_path}")

    logger.info("Code generation complete!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate Python WebDriver BiDi modules from CDDL specification"
    )
    parser.add_argument(
        "cddl_file",
        help="Path to CDDL specification file",
    )
    parser.add_argument(
        "output_dir",
        help="Output directory for generated Python modules",
    )
    parser.add_argument(
        "--version",
        default="1.0",
        help="BiDi spec version (default: 1.0)",
    )
    parser.add_argument(
        "--enhancements-manifest",
        default=None,
        help="Path to enhancement manifest Python file (optional)",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger("generate_bidi").setLevel(logging.DEBUG)

    try:
        main(
            args.cddl_file,
            args.output_dir,
            args.version,
            args.enhancements_manifest,
        )
        sys.exit(0)
    except Exception as e:
        logger.error(f"Generation failed: {e}", exc_info=True)
        sys.exit(1)
