# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: browser
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


@dataclass
class ClientWindowInfo:
    """ClientWindowInfo type type."""

    active: Optional[bool] = None
    client_window: Optional[Any] = None
    height: Optional[Any] = None
    state: Optional[Any] = None
    width: Optional[Any] = None
    x: Optional[Any] = None
    y: Optional[Any] = None


@dataclass
class UserContextInfo:
    """UserContextInfo type type."""

    user_context: Optional[Any] = None


@dataclass
class CreateUserContextParameters:
    """CreateUserContextParameters type type."""

    accept_insecure_certs: Optional[bool] = None
    proxy: Optional[Any] = None
    unhandled_prompt_behavior: Optional[Any] = None


@dataclass
class RemoveUserContextParameters:
    """RemoveUserContextParameters type type."""

    user_context: Optional[Any] = None


@dataclass
class SetClientWindowStateParameters:
    """SetClientWindowStateParameters type type."""

    client_window: Optional[Any] = None


@dataclass
class ClientWindowNamedState:
    """ClientWindowNamedState type type."""

    state: Optional[Any] = None


@dataclass
class ClientWindowRectState:
    """ClientWindowRectState type type."""

    state: Optional[Any] = None
    width: Optional[Any] = None
    height: Optional[Any] = None
    x: Optional[Any] = None
    y: Optional[Any] = None


@dataclass
class SetDownloadBehaviorParameters:
    """SetDownloadBehaviorParameters type type."""

    download_behavior: Optional[Any] = None
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class DownloadBehaviorAllowed:
    """DownloadBehaviorAllowed type type."""

    type: Optional[Any] = None
    destination_folder: Optional[str] = None


@dataclass
class DownloadBehaviorDenied:
    """DownloadBehaviorDenied type type."""

    type: Optional[Any] = None


class Browser:
    """WebDriver BiDi browser module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def close(self) -> Generator[dict, dict, dict]:
        """Execute browser.close."""
        params = {
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browser.close", params)

    def create_user_context(self, accept_insecure_certs: bool = None, proxy: Any = None, unhandled_prompt_behavior: Any = None) -> Generator[dict, dict, dict]:
        """Execute browser.createUserContext."""
        params = {
            "acceptInsecureCerts": accept_insecure_certs,
            "proxy": proxy,
            "unhandledPromptBehavior": unhandled_prompt_behavior,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browser.createUserContext", params)

    def get_client_windows(self) -> Generator[dict, dict, dict]:
        """Execute browser.getClientWindows."""
        params = {
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browser.getClientWindows", params)

    def get_user_contexts(self) -> Generator[dict, dict, dict]:
        """Execute browser.getUserContexts."""
        params = {
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browser.getUserContexts", params)

    def remove_user_context(self, user_context: Any = None) -> Generator[dict, dict, dict]:
        """Execute browser.removeUserContext."""
        params = {
            "userContext": user_context,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browser.removeUserContext", params)

    def set_client_window_state(self, client_window: Any = None) -> Generator[dict, dict, dict]:
        """Execute browser.setClientWindowState."""
        params = {
            "clientWindow": client_window,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browser.setClientWindowState", params)

    def set_download_behavior(self, download_behavior: Any = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute browser.setDownloadBehavior."""
        params = {
            "downloadBehavior": download_behavior,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browser.setDownloadBehavior", params)

