# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: browser
from __future__ import annotations

from typing import Any
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


class ClientWindowState:
    """ClientWindowState enum."""

    ACTIVE = "active"
    BACKGROUND = "background"
    FULLSCREEN = "fullscreen"
    MAXIMIZED = "maximized"
    MINIMIZED = "minimized"
    NORMAL = "normal"


@dataclass
class ClientWindowInfo:
    """ClientWindowInfo type type."""

    active: bool | None = None
    client_window: Any | None = None
    height: Any | None = None
    state: Any | None = None
    width: Any | None = None
    x: Any | None = None
    y: Any | None = None

    def get_client_window(self):
        """Get the client window ID."""
        return self.client_window

    def get_state(self):
        """Get the client window state."""
        return self.state

    def get_width(self):
        """Get the client window width."""
        return self.width

    def get_height(self):
        """Get the client window height."""
        return self.height

    def is_active(self):
        """Check if the client window is active."""
        return self.active

    def get_x(self):
        """Get the client window X position."""
        return self.x

    def get_y(self):
        """Get the client window Y position."""
        return self.y


@dataclass
class UserContextInfo:
    """UserContextInfo type type."""

    user_context: Any | None = None


@dataclass
class CreateUserContextParameters:
    """CreateUserContextParameters type type."""

    accept_insecure_certs: bool | None = None
    proxy: Any | None = None
    unhandled_prompt_behavior: Any | None = None


@dataclass
class GetClientWindowsResult:
    """GetClientWindowsResult type type."""

    client_windows: list[Any | None] | None = field(default_factory=list)


@dataclass
class GetUserContextsResult:
    """GetUserContextsResult type type."""

    user_contexts: list[Any | None] | None = field(default_factory=list)


@dataclass
class RemoveUserContextParameters:
    """RemoveUserContextParameters type type."""

    user_context: Any | None = None


@dataclass
class SetClientWindowStateParameters:
    """SetClientWindowStateParameters type type."""

    client_window: Any | None = None


@dataclass
class ClientWindowNamedState:
    """ClientWindowNamedState type type."""

    state: Any | None = None


@dataclass
class ClientWindowRectState:
    """ClientWindowRectState type type."""

    state: Any | None = None
    width: Any | None = None
    height: Any | None = None
    x: Any | None = None
    y: Any | None = None


@dataclass
class SetDownloadBehaviorParameters:
    """SetDownloadBehaviorParameters type type."""

    download_behavior: Any | None = None
    user_contexts: list[Any | None] | None = field(default_factory=list)


@dataclass
class DownloadBehaviorAllowed:
    """DownloadBehaviorAllowed type type."""

    type: Any | None = None
    destination_folder: str | None = None


@dataclass
class DownloadBehaviorDenied:
    """DownloadBehaviorDenied type type."""

    type: Any | None = None


class Browser:
    """WebDriver BiDi browser module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def close(self):
        """Execute browser.close."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browser.close", params)
        return self._driver.execute(cmd)

    def create_user_context(
        self,
        accept_insecure_certs: bool | None = None,
        proxy: Any | None = None,
        unhandled_prompt_behavior: Any | None = None,
    ):
        """Execute browser.createUserContext and return the user context ID."""
        # Serialize Proxy object if needed
        if proxy and hasattr(proxy, "to_bidi_dict"):
            # It's a Proxy object, use its BiDi serialization method
            proxy = proxy.to_bidi_dict()

        params = {
            "acceptInsecureCerts": accept_insecure_certs,
            "proxy": proxy,
            "unhandledPromptBehavior": unhandled_prompt_behavior,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browser.createUserContext", params)
        result = self._driver.execute(cmd)
        return result.get("userContext") if "userContext" in result else result

    def get_client_windows(self):
        """Execute browser.getClientWindows and return the client windows as ClientWindowInfo objects."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browser.getClientWindows", params)
        result = self._driver.execute(cmd)
        if result and "clientWindows" in result:
            windows = result.get("clientWindows", [])
            # Deserialize dicts to ClientWindowInfo objects
            return [
                (
                    ClientWindowInfo(
                        active=w.get("active"),
                        client_window=w.get("clientWindow"),
                        height=w.get("height"),
                        state=w.get("state"),
                        width=w.get("width"),
                        x=w.get("x"),
                        y=w.get("y"),
                    )
                    if isinstance(w, dict)
                    else w
                )
                for w in windows
            ]
        return []

    def get_user_contexts(self):
        """Execute browser.getUserContexts and return the user context IDs."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browser.getUserContexts", params)
        result = self._driver.execute(cmd)
        if result and "userContexts" in result:
            # Extract just the userContext ID strings from the list of dicts
            user_contexts_list = result.get("userContexts", [])
            return [
                uc.get("userContext")
                for uc in user_contexts_list
                if isinstance(uc, dict)
            ]
        return []

    def remove_user_context(self, user_context: Any | None = None):
        """Execute browser.removeUserContext."""
        params = {
            "userContext": user_context,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browser.removeUserContext", params)
        return self._driver.execute(cmd)

    def set_client_window_state(self, client_window: Any | None = None):
        """Execute browser.setClientWindowState."""
        params = {
            "clientWindow": client_window,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browser.setClientWindowState", params)
        return self._driver.execute(cmd)

    def set_download_behavior(
        self,
        allowed: bool | None = None,
        destination_folder: str | None = None,
        user_contexts: list[Any] | None = None,
    ):
        """Execute browser.setDownloadBehavior."""
        # Validate parameters
        if allowed is True and not destination_folder:
            raise ValueError("destination_folder is required when allowed=True")
        if allowed is False and destination_folder:
            raise ValueError(
                "destination_folder should not be provided when allowed=False"
            )

        # Build download_behavior object
        download_behavior = None
        if allowed is True:
            download_behavior = {
                "type": "allow",
                "destinationFolder": destination_folder,
            }
        elif allowed is False:
            download_behavior = {
                "type": "deny",
            }
        elif allowed is None:
            download_behavior = {
                "type": "allow",
            }

        params = {
            "downloadBehavior": download_behavior,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browser.setDownloadBehavior", params)
        return self._driver.execute(cmd)
