# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: browsingContext
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


class ReadinessState:
    """ReadinessState enum."""

    INTERACTIVE = "interactive"
    COMPLETE = "complete"


@dataclass
class Info:
    """Info type type."""

    children: Optional[Any] = None
    client_window: Optional[Any] = None
    context: Optional[Any] = None
    original_opener: Optional[Any] = None
    url: Optional[str] = None
    user_context: Optional[Any] = None
    parent: Optional[Any] = None


@dataclass
class AccessibilityLocator:
    """AccessibilityLocator type type."""

    type: Optional[Any] = None
    name: Optional[str] = None
    role: Optional[str] = None


@dataclass
class CssLocator:
    """CssLocator type type."""

    type: Optional[Any] = None
    value: Optional[str] = None


@dataclass
class ContextLocator:
    """ContextLocator type type."""

    type: Optional[Any] = None
    context: Optional[Any] = None


@dataclass
class InnerTextLocator:
    """InnerTextLocator type type."""

    type: Optional[Any] = None
    value: Optional[str] = None
    ignore_case: Optional[bool] = None
    match_type: Optional[Any] = None
    max_depth: Optional[Any] = None


@dataclass
class XPathLocator:
    """XPathLocator type type."""

    type: Optional[Any] = None
    value: Optional[str] = None


@dataclass
class BaseNavigationInfo:
    """BaseNavigationInfo type type."""

    context: Optional[Any] = None
    navigation: Optional[Any] = None
    timestamp: Optional[Any] = None
    url: Optional[str] = None


@dataclass
class ActivateParameters:
    """ActivateParameters type type."""

    context: Optional[Any] = None


@dataclass
class CaptureScreenshotParameters:
    """CaptureScreenshotParameters type type."""

    context: Optional[Any] = None
    format: Optional[Any] = None
    clip: Optional[Any] = None


@dataclass
class ImageFormat:
    """ImageFormat type type."""

    type: Optional[str] = None
    quality: Optional[Any] = None


@dataclass
class ElementClipRectangle:
    """ElementClipRectangle type type."""

    type: Optional[Any] = None
    element: Optional[Any] = None


@dataclass
class BoxClipRectangle:
    """BoxClipRectangle type type."""

    type: Optional[Any] = None
    x: Optional[Any] = None
    y: Optional[Any] = None
    width: Optional[Any] = None
    height: Optional[Any] = None


@dataclass
class CaptureScreenshotResult:
    """CaptureScreenshotResult type type."""

    data: Optional[str] = None


@dataclass
class CloseParameters:
    """CloseParameters type type."""

    context: Optional[Any] = None
    prompt_unload: Optional[Any] = None


@dataclass
class CreateParameters:
    """CreateParameters type type."""

    type: Optional[Any] = None
    reference_context: Optional[Any] = None
    background: Optional[Any] = None
    user_context: Optional[Any] = None


@dataclass
class CreateResult:
    """CreateResult type type."""

    context: Optional[Any] = None


@dataclass
class GetTreeParameters:
    """GetTreeParameters type type."""

    max_depth: Optional[Any] = None
    root: Optional[Any] = None


@dataclass
class GetTreeResult:
    """GetTreeResult type type."""

    contexts: Optional[Any] = None


@dataclass
class HandleUserPromptParameters:
    """HandleUserPromptParameters type type."""

    context: Optional[Any] = None
    accept: Optional[bool] = None
    user_text: Optional[str] = None


@dataclass
class LocateNodesParameters:
    """LocateNodesParameters type type."""

    context: Optional[Any] = None
    locator: Optional[Any] = None
    serialization_options: Optional[Any] = None
    start_nodes: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class LocateNodesResult:
    """LocateNodesResult type type."""

    nodes: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class NavigateParameters:
    """NavigateParameters type type."""

    context: Optional[Any] = None
    url: Optional[str] = None
    wait: Optional[Any] = None


@dataclass
class NavigateResult:
    """NavigateResult type type."""

    navigation: Optional[Any] = None
    url: Optional[str] = None


@dataclass
class PrintParameters:
    """PrintParameters type type."""

    context: Optional[Any] = None
    background: Optional[Any] = None
    margin: Optional[Any] = None
    page: Optional[Any] = None
    shrink_to_fit: Optional[Any] = None


@dataclass
class PrintResult:
    """PrintResult type type."""

    data: Optional[str] = None


@dataclass
class ReloadParameters:
    """ReloadParameters type type."""

    context: Optional[Any] = None
    ignore_cache: Optional[bool] = None
    wait: Optional[Any] = None


@dataclass
class SetViewportParameters:
    """SetViewportParameters type type."""

    context: Optional[Any] = None
    viewport: Optional[Any] = None
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class Viewport:
    """Viewport type type."""

    width: Optional[Any] = None
    height: Optional[Any] = None


@dataclass
class TraverseHistoryParameters:
    """TraverseHistoryParameters type type."""

    context: Optional[Any] = None
    delta: Optional[Any] = None


@dataclass
class HistoryUpdatedParameters:
    """HistoryUpdatedParameters type type."""

    context: Optional[Any] = None
    timestamp: Optional[Any] = None
    url: Optional[str] = None


@dataclass
class DownloadWillBeginParams:
    """DownloadWillBeginParams type type."""

    suggested_filename: Optional[str] = None


@dataclass
class DownloadCanceledParams:
    """DownloadCanceledParams type type."""

    status: Optional[Any] = None


@dataclass
class DownloadCompleteParams:
    """DownloadCompleteParams type type."""

    status: Optional[Any] = None
    filepath: Optional[Any] = None


@dataclass
class UserPromptClosedParameters:
    """UserPromptClosedParameters type type."""

    context: Optional[Any] = None
    accepted: Optional[bool] = None
    type: Optional[Any] = None
    user_text: Optional[str] = None


@dataclass
class UserPromptOpenedParameters:
    """UserPromptOpenedParameters type type."""

    context: Optional[Any] = None
    handler: Optional[Any] = None
    message: Optional[str] = None
    type: Optional[Any] = None
    default_value: Optional[str] = None


class BrowsingContext:
    """WebDriver BiDi browsingContext module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def activate(self, context: Any = None) -> Generator[dict, dict, dict]:
        """Execute browsingContext.activate."""
        params = {
            "context": context,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.activate", params)

    def capture_screenshot(
        self, context: Any = None, format: Any = None, clip: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.captureScreenshot."""
        params = {
            "context": context,
            "format": format,
            "clip": clip,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.captureScreenshot", params)

    def close(
        self, context: Any = None, prompt_unload: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.close."""
        params = {
            "context": context,
            "promptUnload": prompt_unload,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.close", params)

    def create(
        self,
        type: Any = None,
        reference_context: Any = None,
        background: Any = None,
        user_context: Any = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.create."""
        params = {
            "type": type,
            "referenceContext": reference_context,
            "background": background,
            "userContext": user_context,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.create", params)

    def get_tree(
        self, max_depth: Any = None, root: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.getTree."""
        params = {
            "maxDepth": max_depth,
            "root": root,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.getTree", params)

    def handle_user_prompt(
        self, context: Any = None, accept: bool = None, user_text: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.handleUserPrompt."""
        params = {
            "context": context,
            "accept": accept,
            "userText": user_text,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.handleUserPrompt", params)

    def locate_nodes(
        self,
        context: Any = None,
        locator: Any = None,
        serialization_options: Any = None,
        start_nodes: List[Any] = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.locateNodes."""
        params = {
            "context": context,
            "locator": locator,
            "serializationOptions": serialization_options,
            "startNodes": start_nodes,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.locateNodes", params)

    def navigate(
        self, context: Any = None, url: Any = None, wait: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.navigate."""
        params = {
            "context": context,
            "url": url,
            "wait": wait,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.navigate", params)

    def print(
        self,
        context: Any = None,
        background: Any = None,
        margin: Any = None,
        page: Any = None,
        shrink_to_fit: Any = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.print."""
        params = {
            "context": context,
            "background": background,
            "margin": margin,
            "page": page,
            "shrinkToFit": shrink_to_fit,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.print", params)

    def reload(
        self, context: Any = None, ignore_cache: bool = None, wait: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.reload."""
        params = {
            "context": context,
            "ignoreCache": ignore_cache,
            "wait": wait,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.reload", params)

    def set_viewport(
        self, context: Any = None, viewport: Any = None, user_contexts: List[Any] = None
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.setViewport."""
        params = {
            "context": context,
            "viewport": viewport,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.setViewport", params)

    def traverse_history(
        self, context: Any = None, delta: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.traverseHistory."""
        params = {
            "context": context,
            "delta": delta,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.traverseHistory", params)

    def context_created(
        self,
        children: Any = None,
        client_window: Any = None,
        context: Any = None,
        original_opener: Any = None,
        url: Any = None,
        user_context: Any = None,
        parent: Any = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.contextCreated."""
        params = {
            "children": children,
            "clientWindow": client_window,
            "context": context,
            "originalOpener": original_opener,
            "url": url,
            "userContext": user_context,
            "parent": parent,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.contextCreated", params)

    def context_destroyed(
        self,
        children: Any = None,
        client_window: Any = None,
        context: Any = None,
        original_opener: Any = None,
        url: Any = None,
        user_context: Any = None,
        parent: Any = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.contextDestroyed."""
        params = {
            "children": children,
            "clientWindow": client_window,
            "context": context,
            "originalOpener": original_opener,
            "url": url,
            "userContext": user_context,
            "parent": parent,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.contextDestroyed", params)

    def navigation_started(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.navigationStarted."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.navigationStarted", params)

    def fragment_navigated(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.fragmentNavigated."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.fragmentNavigated", params)

    def history_updated(
        self, context: Any = None, timestamp: Any = None, url: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.historyUpdated."""
        params = {
            "context": context,
            "timestamp": timestamp,
            "url": url,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.historyUpdated", params)

    def dom_content_loaded(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.domContentLoaded."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.domContentLoaded", params)

    def load(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.load."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.load", params)

    def download_will_begin(
        self, suggested_filename: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.downloadWillBegin."""
        params = {
            "suggestedFilename": suggested_filename,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.downloadWillBegin", params)

    def download_end(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.downloadEnd."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.downloadEnd", params)

    def navigation_aborted(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.navigationAborted."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.navigationAborted", params)

    def navigation_committed(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.navigationCommitted."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.navigationCommitted", params)

    def navigation_failed(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.navigationFailed."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.navigationFailed", params)

    def user_prompt_closed(
        self,
        context: Any = None,
        accepted: bool = None,
        type: Any = None,
        user_text: Any = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.userPromptClosed."""
        params = {
            "context": context,
            "accepted": accepted,
            "type": type,
            "userText": user_text,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.userPromptClosed", params)

    def user_prompt_opened(
        self,
        context: Any = None,
        handler: Any = None,
        message: Any = None,
        type: Any = None,
        default_value: Any = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.userPromptOpened."""
        params = {
            "context": context,
            "handler": handler,
            "message": message,
            "type": type,
            "defaultValue": default_value,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.userPromptOpened", params)
