# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: browsingContext
from __future__ import annotations

from typing import Any
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


class ReadinessState:
    """ReadinessState enum."""

    INTERACTIVE = "interactive"
    COMPLETE = "complete"


@dataclass
class Info:
    """Info type type."""

    children: Any | None = None
    client_window: Any | None = None
    context: Any | None = None
    original_opener: Any | None = None
    url: str | None = None
    user_context: Any | None = None
    parent: Any | None = None


@dataclass
class AccessibilityLocator:
    """AccessibilityLocator type type."""

    type: Any | None = None
    name: str | None = None
    role: str | None = None


@dataclass
class CssLocator:
    """CssLocator type type."""

    type: Any | None = None
    value: str | None = None


@dataclass
class ContextLocator:
    """ContextLocator type type."""

    type: Any | None = None
    context: Any | None = None


@dataclass
class InnerTextLocator:
    """InnerTextLocator type type."""

    type: Any | None = None
    value: str | None = None
    ignore_case: bool | None = None
    match_type: Any | None = None
    max_depth: Any | None = None


@dataclass
class XPathLocator:
    """XPathLocator type type."""

    type: Any | None = None
    value: str | None = None


@dataclass
class BaseNavigationInfo:
    """BaseNavigationInfo type type."""

    context: Any | None = None
    navigation: Any | None = None
    timestamp: Any | None = None
    url: str | None = None


@dataclass
class ActivateParameters:
    """ActivateParameters type type."""

    context: Any | None = None


@dataclass
class CaptureScreenshotParameters:
    """CaptureScreenshotParameters type type."""

    context: Any | None = None
    format: Any | None = None
    clip: Any | None = None


@dataclass
class ImageFormat:
    """ImageFormat type type."""

    type: str | None = None
    quality: Any | None = None


@dataclass
class ElementClipRectangle:
    """ElementClipRectangle type type."""

    type: Any | None = None
    element: Any | None = None


@dataclass
class BoxClipRectangle:
    """BoxClipRectangle type type."""

    type: Any | None = None
    x: Any | None = None
    y: Any | None = None
    width: Any | None = None
    height: Any | None = None


@dataclass
class CaptureScreenshotResult:
    """CaptureScreenshotResult type type."""

    data: str | None = None


@dataclass
class CloseParameters:
    """CloseParameters type type."""

    context: Any | None = None
    prompt_unload: Any | None = None


@dataclass
class CreateParameters:
    """CreateParameters type type."""

    type: Any | None = None
    reference_context: Any | None = None
    background: Any | None = None
    user_context: Any | None = None


@dataclass
class CreateResult:
    """CreateResult type type."""

    context: Any | None = None


@dataclass
class GetTreeParameters:
    """GetTreeParameters type type."""

    max_depth: Any | None = None
    root: Any | None = None


@dataclass
class GetTreeResult:
    """GetTreeResult type type."""

    contexts: Any | None = None


@dataclass
class HandleUserPromptParameters:
    """HandleUserPromptParameters type type."""

    context: Any | None = None
    accept: bool | None = None
    user_text: str | None = None


@dataclass
class LocateNodesParameters:
    """LocateNodesParameters type type."""

    context: Any | None = None
    locator: Any | None = None
    serialization_options: Any | None = None
    start_nodes: list[Any | None] | None = field(default_factory=list)


@dataclass
class LocateNodesResult:
    """LocateNodesResult type type."""

    nodes: list[Any | None] | None = field(default_factory=list)


@dataclass
class NavigateParameters:
    """NavigateParameters type type."""

    context: Any | None = None
    url: str | None = None
    wait: Any | None = None


@dataclass
class NavigateResult:
    """NavigateResult type type."""

    navigation: Any | None = None
    url: str | None = None


@dataclass
class PrintParameters:
    """PrintParameters type type."""

    context: Any | None = None
    background: Any | None = None
    margin: Any | None = None
    page: Any | None = None
    shrink_to_fit: Any | None = None


@dataclass
class PrintResult:
    """PrintResult type type."""

    data: str | None = None


@dataclass
class ReloadParameters:
    """ReloadParameters type type."""

    context: Any | None = None
    ignore_cache: bool | None = None
    wait: Any | None = None


@dataclass
class SetViewportParameters:
    """SetViewportParameters type type."""

    context: Any | None = None
    viewport: Any | None = None
    user_contexts: list[Any | None] | None = field(default_factory=list)


@dataclass
class Viewport:
    """Viewport type type."""

    width: Any | None = None
    height: Any | None = None


@dataclass
class TraverseHistoryParameters:
    """TraverseHistoryParameters type type."""

    context: Any | None = None
    delta: Any | None = None


@dataclass
class HistoryUpdatedParameters:
    """HistoryUpdatedParameters type type."""

    context: Any | None = None
    timestamp: Any | None = None
    url: str | None = None


@dataclass
class DownloadWillBeginParams:
    """DownloadWillBeginParams type type."""

    suggested_filename: str | None = None


@dataclass
class DownloadCanceledParams:
    """DownloadCanceledParams type type."""

    status: Any | None = None


@dataclass
class DownloadCompleteParams:
    """DownloadCompleteParams type type."""

    status: Any | None = None
    filepath: Any | None = None


@dataclass
class UserPromptClosedParameters:
    """UserPromptClosedParameters type type."""

    context: Any | None = None
    accepted: bool | None = None
    type: Any | None = None
    user_text: str | None = None


@dataclass
class UserPromptOpenedParameters:
    """UserPromptOpenedParameters type type."""

    context: Any | None = None
    handler: Any | None = None
    message: str | None = None
    type: Any | None = None
    default_value: str | None = None


class BrowsingContext:
    """WebDriver BiDi browsingContext module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def activate(self, context: Any | None = None):
        """Execute browsingContext.activate."""
        params = {
            "context": context,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.activate", params)
        return self._driver.execute(cmd)

    def capture_screenshot(
        self,
        context: Any | None = None,
        format: Any | None = None,
        clip: Any | None = None,
    ):
        """Execute browsingContext.captureScreenshot."""
        params = {
            "context": context,
            "format": format,
            "clip": clip,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.captureScreenshot", params)
        return self._driver.execute(cmd)

    def close(self, context: Any | None = None, prompt_unload: Any | None = None):
        """Execute browsingContext.close."""
        params = {
            "context": context,
            "promptUnload": prompt_unload,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.close", params)
        return self._driver.execute(cmd)

    def create(
        self,
        type: Any | None = None,
        reference_context: Any | None = None,
        background: Any | None = None,
        user_context: Any | None = None,
    ):
        """Execute browsingContext.create and return the context info."""
        params = {
            "type": type,
            "referenceContext": reference_context,
            "background": background,
            "userContext": user_context,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.create", params)
        result = self._driver.execute(cmd)
        return result.get("context") if "context" in result else result

    def get_tree(self, max_depth: Any | None = None, root: Any | None = None):
        """Execute browsingContext.getTree."""
        params = {
            "maxDepth": max_depth,
            "root": root,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.getTree", params)
        return self._driver.execute(cmd)

    def handle_user_prompt(
        self,
        context: Any | None = None,
        accept: bool | None = None,
        user_text: Any | None = None,
    ):
        """Execute browsingContext.handleUserPrompt."""
        params = {
            "context": context,
            "accept": accept,
            "userText": user_text,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.handleUserPrompt", params)
        return self._driver.execute(cmd)

    def locate_nodes(
        self,
        context: Any | None = None,
        locator: Any | None = None,
        serialization_options: Any | None = None,
        start_nodes: list[Any] = None,
    ):
        """Execute browsingContext.locateNodes."""
        params = {
            "context": context,
            "locator": locator,
            "serializationOptions": serialization_options,
            "startNodes": start_nodes,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.locateNodes", params)
        return self._driver.execute(cmd)

    def navigate(
        self,
        context: Any | None = None,
        url: Any | None = None,
        wait: Any | None = None,
    ):
        """Execute browsingContext.navigate."""
        params = {
            "context": context,
            "url": url,
            "wait": wait,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.navigate", params)
        return self._driver.execute(cmd)

    def print(
        self,
        context: Any | None = None,
        background: Any | None = None,
        margin: Any | None = None,
        page: Any | None = None,
        shrink_to_fit: Any | None = None,
    ):
        """Execute browsingContext.print."""
        params = {
            "context": context,
            "background": background,
            "margin": margin,
            "page": page,
            "shrinkToFit": shrink_to_fit,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.print", params)
        return self._driver.execute(cmd)

    def reload(
        self,
        context: Any | None = None,
        ignore_cache: bool | None = None,
        wait: Any | None = None,
    ):
        """Execute browsingContext.reload."""
        params = {
            "context": context,
            "ignoreCache": ignore_cache,
            "wait": wait,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.reload", params)
        return self._driver.execute(cmd)

    def set_viewport(
        self,
        context: Any | None = None,
        viewport: Any | None = None,
        user_contexts: list[Any] = None,
    ):
        """Execute browsingContext.setViewport."""
        params = {
            "context": context,
            "viewport": viewport,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.setViewport", params)
        return self._driver.execute(cmd)

    def traverse_history(self, context: Any | None = None, delta: Any | None = None):
        """Execute browsingContext.traverseHistory."""
        params = {
            "context": context,
            "delta": delta,
        }
        params = {k: v for k, v in params.items() if v is not None}
        cmd = command_builder("browsingContext.traverseHistory", params)
        return self._driver.execute(cmd)

    def context_created(
        self,
        children: Any | None = None,
        client_window: Any | None = None,
        context: Any | None = None,
        original_opener: Any | None = None,
        url: Any | None = None,
        user_context: Any | None = None,
        parent: Any | None = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.contextCreated."""
        params = {
            "children": children,
            "clientWindow": client_window,
            "context": context,
            "originalOpener": original_opener,
            "url": url,
            "userContext": user_context,
            "parent": parent,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.contextCreated", params)

    def context_destroyed(
        self,
        children: Any | None = None,
        client_window: Any | None = None,
        context: Any | None = None,
        original_opener: Any | None = None,
        url: Any | None = None,
        user_context: Any | None = None,
        parent: Any | None = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.contextDestroyed."""
        params = {
            "children": children,
            "clientWindow": client_window,
            "context": context,
            "originalOpener": original_opener,
            "url": url,
            "userContext": user_context,
            "parent": parent,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.contextDestroyed", params)

    def navigation_started(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.navigationStarted."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.navigationStarted", params)

    def fragment_navigated(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.fragmentNavigated."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.fragmentNavigated", params)

    def history_updated(
        self,
        context: Any | None = None,
        timestamp: Any | None = None,
        url: Any | None = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.historyUpdated."""
        params = {
            "context": context,
            "timestamp": timestamp,
            "url": url,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.historyUpdated", params)

    def dom_content_loaded(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.domContentLoaded."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.domContentLoaded", params)

    def load(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.load."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.load", params)

    def download_will_begin(
        self, suggested_filename: Any | None = None
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.downloadWillBegin."""
        params = {
            "suggestedFilename": suggested_filename,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.downloadWillBegin", params)

    def download_end(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.downloadEnd."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.downloadEnd", params)

    def navigation_aborted(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.navigationAborted."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.navigationAborted", params)

    def navigation_committed(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.navigationCommitted."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.navigationCommitted", params)

    def navigation_failed(self) -> Generator[dict, dict, dict]:
        """Execute browsingContext.navigationFailed."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.navigationFailed", params)

    def user_prompt_closed(
        self,
        context: Any | None = None,
        accepted: bool | None = None,
        type: Any | None = None,
        user_text: Any | None = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.userPromptClosed."""
        params = {
            "context": context,
            "accepted": accepted,
            "type": type,
            "userText": user_text,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.userPromptClosed", params)

    def user_prompt_opened(
        self,
        context: Any | None = None,
        handler: Any | None = None,
        message: Any | None = None,
        type: Any | None = None,
        default_value: Any | None = None,
    ) -> Generator[dict, dict, dict]:
        """Execute browsingContext.userPromptOpened."""
        params = {
            "context": context,
            "handler": handler,
            "message": message,
            "type": type,
            "defaultValue": default_value,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("browsingContext.userPromptOpened", params)
