# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: emulation
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


@dataclass
class SetForcedColorsModeThemeOverrideParameters:
    """SetForcedColorsModeThemeOverrideParameters type type."""

    theme: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class SetGeolocationOverrideParameters:
    """SetGeolocationOverrideParameters type type."""

    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class GeolocationCoordinates:
    """GeolocationCoordinates type type."""

    latitude: Optional[Any] = None
    longitude: Optional[Any] = None
    altitude: Optional[Any] = None


@dataclass
class GeolocationPositionError:
    """GeolocationPositionError type type."""

    type: Optional[Any] = None


@dataclass
class SetLocaleOverrideParameters:
    """SetLocaleOverrideParameters type type."""

    locale: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class setNetworkConditionsParameters:
    """setNetworkConditionsParameters type type."""

    network_conditions: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class NetworkConditionsOffline:
    """NetworkConditionsOffline type type."""

    type: Optional[Any] = None


@dataclass
class ScreenArea:
    """ScreenArea type type."""

    width: Optional[Any] = None
    height: Optional[Any] = None


@dataclass
class SetScreenSettingsOverrideParameters:
    """SetScreenSettingsOverrideParameters type type."""

    screen_area: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class ScreenOrientation:
    """ScreenOrientation type type."""

    natural: Optional[Any] = None
    type: Optional[Any] = None


@dataclass
class SetScreenOrientationOverrideParameters:
    """SetScreenOrientationOverrideParameters type type."""

    screen_orientation: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class SetUserAgentOverrideParameters:
    """SetUserAgentOverrideParameters type type."""

    user_agent: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class SetViewportMetaOverrideParameters:
    """SetViewportMetaOverrideParameters type type."""

    viewport_meta: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class SetScriptingEnabledParameters:
    """SetScriptingEnabledParameters type type."""

    enabled: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class SetScrollbarTypeOverrideParameters:
    """SetScrollbarTypeOverrideParameters type type."""

    scrollbar_type: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class SetTimezoneOverrideParameters:
    """SetTimezoneOverrideParameters type type."""

    timezone: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class SetTouchOverrideParameters:
    """SetTouchOverrideParameters type type."""

    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


class Emulation:
    """WebDriver BiDi emulation module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def set_forced_colors_mode_theme_override(self, theme: Any = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setForcedColorsModeThemeOverride."""
        params = {
            "theme": theme,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setForcedColorsModeThemeOverride", params)

    def set_geolocation_override(self, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setGeolocationOverride."""
        params = {
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setGeolocationOverride", params)

    def set_locale_override(self, locale: Any = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setLocaleOverride."""
        params = {
            "locale": locale,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setLocaleOverride", params)

    def set_network_conditions(self, network_conditions: Any = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setNetworkConditions."""
        params = {
            "networkConditions": network_conditions,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setNetworkConditions", params)

    def set_screen_settings_override(self, screen_area: Any = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setScreenSettingsOverride."""
        params = {
            "screenArea": screen_area,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setScreenSettingsOverride", params)

    def set_screen_orientation_override(self, screen_orientation: Any = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setScreenOrientationOverride."""
        params = {
            "screenOrientation": screen_orientation,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setScreenOrientationOverride", params)

    def set_user_agent_override(self, user_agent: Any = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setUserAgentOverride."""
        params = {
            "userAgent": user_agent,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setUserAgentOverride", params)

    def set_viewport_meta_override(self, viewport_meta: Any = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setViewportMetaOverride."""
        params = {
            "viewportMeta": viewport_meta,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setViewportMetaOverride", params)

    def set_scripting_enabled(self, enabled: Any = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setScriptingEnabled."""
        params = {
            "enabled": enabled,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setScriptingEnabled", params)

    def set_scrollbar_type_override(self, scrollbar_type: Any = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setScrollbarTypeOverride."""
        params = {
            "scrollbarType": scrollbar_type,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setScrollbarTypeOverride", params)

    def set_timezone_override(self, timezone: Any = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setTimezoneOverride."""
        params = {
            "timezone": timezone,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setTimezoneOverride", params)

    def set_touch_override(self, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute emulation.setTouchOverride."""
        params = {
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("emulation.setTouchOverride", params)

