# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: input
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


@dataclass
class ElementOrigin:
    """ElementOrigin type type."""

    type: Optional[Any] = None
    element: Optional[Any] = None


@dataclass
class PerformActionsParameters:
    """PerformActionsParameters type type."""

    context: Optional[Any] = None
    actions: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class NoneSourceActions:
    """NoneSourceActions type type."""

    type: Optional[Any] = None
    id: Optional[str] = None
    actions: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class KeySourceActions:
    """KeySourceActions type type."""

    type: Optional[Any] = None
    id: Optional[str] = None
    actions: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class PointerSourceActions:
    """PointerSourceActions type type."""

    type: Optional[Any] = None
    id: Optional[str] = None
    parameters: Optional[Any] = None
    actions: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class PointerParameters:
    """PointerParameters type type."""

    pointer_type: Optional[Any] = None


@dataclass
class WheelSourceActions:
    """WheelSourceActions type type."""

    type: Optional[Any] = None
    id: Optional[str] = None
    actions: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class PauseAction:
    """PauseAction type type."""

    type: Optional[Any] = None
    duration: Optional[Any] = None


@dataclass
class KeyDownAction:
    """KeyDownAction type type."""

    type: Optional[Any] = None
    value: Optional[str] = None


@dataclass
class KeyUpAction:
    """KeyUpAction type type."""

    type: Optional[Any] = None
    value: Optional[str] = None


@dataclass
class PointerUpAction:
    """PointerUpAction type type."""

    type: Optional[Any] = None
    button: Optional[Any] = None


@dataclass
class PointerDownAction:
    """PointerDownAction type type."""

    type: Optional[Any] = None
    button: Optional[Any] = None


@dataclass
class PointerMoveAction:
    """PointerMoveAction type type."""

    type: Optional[Any] = None
    x: Optional[Any] = None
    y: Optional[Any] = None
    duration: Optional[Any] = None
    origin: Optional[Any] = None


@dataclass
class WheelScrollAction:
    """WheelScrollAction type type."""

    type: Optional[Any] = None
    x: Optional[Any] = None
    y: Optional[Any] = None
    delta_x: Optional[Any] = None
    delta_y: Optional[Any] = None
    duration: Optional[Any] = None
    origin: Optional[Any] = None


@dataclass
class PointerCommonProperties:
    """PointerCommonProperties type type."""

    width: Optional[Any] = None
    height: Optional[Any] = None
    pressure: Optional[Any] = None
    tangential_pressure: Optional[Any] = None


@dataclass
class ReleaseActionsParameters:
    """ReleaseActionsParameters type type."""

    context: Optional[Any] = None


@dataclass
class SetFilesParameters:
    """SetFilesParameters type type."""

    context: Optional[Any] = None
    element: Optional[Any] = None
    files: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class FileDialogInfo:
    """FileDialogInfo type type."""

    context: Optional[Any] = None
    element: Optional[Any] = None
    multiple: Optional[bool] = None


class Input:
    """WebDriver BiDi input module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def perform_actions(self, context: Any = None, actions: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute input.performActions."""
        params = {
            "context": context,
            "actions": actions,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("input.performActions", params)

    def release_actions(self, context: Any = None) -> Generator[dict, dict, dict]:
        """Execute input.releaseActions."""
        params = {
            "context": context,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("input.releaseActions", params)

    def set_files(self, context: Any = None, element: Any = None, files: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute input.setFiles."""
        params = {
            "context": context,
            "element": element,
            "files": files,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("input.setFiles", params)

    def file_dialog_opened(self, context: Any = None, element: Any = None, multiple: bool = None) -> Generator[dict, dict, dict]:
        """Execute input.fileDialogOpened."""
        params = {
            "context": context,
            "element": element,
            "multiple": multiple,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("input.fileDialogOpened", params)

