# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: input
from __future__ import annotations

from typing import Any
from .common import command_builder
from dataclasses import field
from typing import Any
from dataclasses import dataclass


class Origin:
    """Pointer origin type."""

    VIEWPORT = "viewport"
    POINTER = "pointer"


class PointerType:
    """Pointer type enum."""

    MOUSE = "mouse"
    PEN = "pen"
    TOUCH = "touch"


@dataclass
class ElementOrigin:
    """ElementOrigin type type."""

    type: Any | None = None
    element: Any | None = None


@dataclass
class PerformActionsParameters:
    """PerformActionsParameters type type."""

    context: Any | None = None
    actions: list[Any | None] | None = field(default_factory=list)


@dataclass
class NoneSourceActions:
    """NoneSourceActions type type."""

    type: Any | None = None
    id: str | None = None
    actions: list[Any | None] | None = field(default_factory=list)


@dataclass
class KeySourceActions:
    """KeySourceActions type type."""

    type: Any | None = None
    id: str | None = None
    actions: list[Any | None] | None = field(default_factory=list)


@dataclass
class PointerSourceActions:
    """PointerSourceActions type type."""

    type: Any | None = None
    id: str | None = None
    parameters: Any | None = None
    actions: list[Any | None] | None = field(default_factory=list)


@dataclass
class PointerParameters:
    """PointerParameters type type."""

    pointer_type: Any | None = None


@dataclass
class WheelSourceActions:
    """WheelSourceActions type type."""

    type: Any | None = None
    id: str | None = None
    actions: list[Any | None] | None = field(default_factory=list)


@dataclass
class PauseAction:
    """PauseAction type type."""

    type: Any | None = None
    duration: Any | None = None


@dataclass
class KeyDownAction:
    """KeyDownAction type type."""

    type: Any | None = None
    value: str | None = None


@dataclass
class KeyUpAction:
    """KeyUpAction type type."""

    type: Any | None = None
    value: str | None = None


@dataclass
class PointerUpAction:
    """PointerUpAction type type."""

    type: Any | None = None
    button: Any | None = None


@dataclass
class PointerDownAction:
    """PointerDownAction type type."""

    type: Any | None = None
    button: Any | None = None


@dataclass
class PointerMoveAction:
    """PointerMoveAction type type."""

    type: Any | None = None
    x: Any | None = None
    y: Any | None = None
    duration: Any | None = None
    origin: Any | None = None


@dataclass
class WheelScrollAction:
    """WheelScrollAction type type."""

    type: Any | None = None
    x: Any | None = None
    y: Any | None = None
    delta_x: Any | None = None
    delta_y: Any | None = None
    duration: Any | None = None
    origin: Any | None = None


@dataclass
class PointerCommonProperties:
    """PointerCommonProperties type type."""

    width: Any | None = None
    height: Any | None = None
    pressure: Any | None = None
    tangential_pressure: Any | None = None


@dataclass
class ReleaseActionsParameters:
    """ReleaseActionsParameters type type."""

    context: Any | None = None


@dataclass
class SetFilesParameters:
    """SetFilesParameters type type."""

    context: Any | None = None
    element: Any | None = None
    files: list[Any | None] | None = field(default_factory=list)


@dataclass
class FileDialogInfo:
    """FileDialogInfo type type."""

    context: Any | None = None
    element: Any | None = None
    multiple: bool | None = None


class Input:
    """WebDriver BiDi input module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def perform_actions(
        self, context: Any = None, actions: list[Any] = None
    ) -> Generator[dict, dict, dict]:
        """Execute input.performActions."""
        params = {
            "context": context,
            "actions": actions,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("input.performActions", params)

    def release_actions(self, context: Any = None) -> Generator[dict, dict, dict]:
        """Execute input.releaseActions."""
        params = {
            "context": context,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("input.releaseActions", params)

    def set_files(
        self, context: Any = None, element: Any = None, files: list[Any] = None
    ) -> Generator[dict, dict, dict]:
        """Execute input.setFiles."""
        params = {
            "context": context,
            "element": element,
            "files": files,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("input.setFiles", params)

    def file_dialog_opened(
        self, context: Any = None, element: Any = None, multiple: bool = None
    ) -> Generator[dict, dict, dict]:
        """Execute input.fileDialogOpened."""
        params = {
            "context": context,
            "element": element,
            "multiple": multiple,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("input.fileDialogOpened", params)
