# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: network
from __future__ import annotations

from typing import Any
from .common import command_builder
from dataclasses import field
from typing import Any
from dataclasses import dataclass


@dataclass
class AuthChallenge:
    """AuthChallenge type type."""

    scheme: str | None = None
    realm: str | None = None


@dataclass
class AuthCredentials:
    """AuthCredentials type type."""

    type: Any | None = None
    username: str | None = None
    password: str | None = None


@dataclass
class BaseParameters:
    """BaseParameters type type."""

    context: Any | None = None
    is_blocked: bool | None = None
    navigation: Any | None = None
    redirect_count: Any | None = None
    request: Any | None = None
    timestamp: Any | None = None
    intercepts: list[Any | None] | None = field(default_factory=list)


@dataclass
class StringValue:
    """StringValue type type."""

    type: Any | None = None
    value: str | None = None


@dataclass
class Base64Value:
    """Base64Value type type."""

    type: Any | None = None
    value: str | None = None


@dataclass
class Cookie:
    """Cookie type type."""

    name: str | None = None
    value: Any | None = None
    domain: str | None = None
    path: str | None = None
    size: Any | None = None
    http_only: bool | None = None
    secure: bool | None = None
    same_site: Any | None = None
    expiry: Any | None = None


@dataclass
class CookieHeader:
    """CookieHeader type type."""

    name: str | None = None
    value: Any | None = None


@dataclass
class FetchTimingInfo:
    """FetchTimingInfo type type."""

    time_origin: Any | None = None
    request_time: Any | None = None
    redirect_start: Any | None = None
    redirect_end: Any | None = None
    fetch_start: Any | None = None
    dns_start: Any | None = None
    dns_end: Any | None = None
    connect_start: Any | None = None
    connect_end: Any | None = None
    tls_start: Any | None = None
    request_start: Any | None = None
    response_start: Any | None = None
    response_end: Any | None = None


@dataclass
class Header:
    """Header type type."""

    name: str | None = None
    value: Any | None = None


@dataclass
class Initiator:
    """Initiator type type."""

    column_number: Any | None = None
    line_number: Any | None = None
    request: Any | None = None
    stack_trace: Any | None = None
    type: Any | None = None


@dataclass
class ResponseContent:
    """ResponseContent type type."""

    size: Any | None = None


@dataclass
class ResponseData:
    """ResponseData type type."""

    url: str | None = None
    protocol: str | None = None
    status: Any | None = None
    status_text: str | None = None
    from_cache: bool | None = None
    headers: list[Any | None] | None = field(default_factory=list)
    mime_type: str | None = None
    bytes_received: Any | None = None
    headers_size: Any | None = None
    body_size: Any | None = None
    content: Any | None = None
    auth_challenges: list[Any | None] | None = field(default_factory=list)


@dataclass
class SetCookieHeader:
    """SetCookieHeader type type."""

    name: str | None = None
    value: Any | None = None
    domain: str | None = None
    http_only: bool | None = None
    expiry: str | None = None
    max_age: Any | None = None
    path: str | None = None
    same_site: Any | None = None
    secure: bool | None = None


@dataclass
class UrlPatternPattern:
    """UrlPatternPattern type type."""

    type: Any | None = None
    protocol: str | None = None
    hostname: str | None = None
    port: str | None = None
    pathname: str | None = None
    search: str | None = None


@dataclass
class UrlPatternString:
    """UrlPatternString type type."""

    type: Any | None = None
    pattern: str | None = None


@dataclass
class AddDataCollectorParameters:
    """AddDataCollectorParameters type type."""

    data_types: list[Any | None] | None = field(default_factory=list)
    max_encoded_data_size: Any | None = None
    collector_type: Any | None = None
    contexts: list[Any | None] | None = field(default_factory=list)
    user_contexts: list[Any | None] | None = field(default_factory=list)


@dataclass
class AddDataCollectorResult:
    """AddDataCollectorResult type type."""

    collector: Any | None = None


@dataclass
class AddInterceptParameters:
    """AddInterceptParameters type type."""

    phases: list[Any | None] | None = field(default_factory=list)
    contexts: list[Any | None] | None = field(default_factory=list)
    url_patterns: list[Any | None] | None = field(default_factory=list)


@dataclass
class AddInterceptResult:
    """AddInterceptResult type type."""

    intercept: Any | None = None


@dataclass
class ContinueResponseParameters:
    """ContinueResponseParameters type type."""

    request: Any | None = None
    cookies: list[Any | None] | None = field(default_factory=list)
    credentials: Any | None = None
    headers: list[Any | None] | None = field(default_factory=list)
    reason_phrase: str | None = None
    status_code: Any | None = None


@dataclass
class ContinueWithAuthParameters:
    """ContinueWithAuthParameters type type."""

    request: Any | None = None


@dataclass
class ContinueWithAuthCredentials:
    """ContinueWithAuthCredentials type type."""

    action: Any | None = None
    credentials: Any | None = None


@dataclass
class ContinueWithAuthNoCredentials:
    """ContinueWithAuthNoCredentials type type."""

    action: Any | None = None


@dataclass
class disownDataParameters:
    """disownDataParameters type type."""

    data_type: Any | None = None
    collector: Any | None = None
    request: Any | None = None


@dataclass
class FailRequestParameters:
    """FailRequestParameters type type."""

    request: Any | None = None


@dataclass
class GetDataParameters:
    """GetDataParameters type type."""

    data_type: Any | None = None
    collector: Any | None = None
    disown: Any | None = None
    request: Any | None = None


@dataclass
class GetDataResult:
    """GetDataResult type type."""

    bytes: Any | None = None


@dataclass
class ProvideResponseParameters:
    """ProvideResponseParameters type type."""

    request: Any | None = None
    body: Any | None = None
    cookies: list[Any | None] | None = field(default_factory=list)
    headers: list[Any | None] | None = field(default_factory=list)
    reason_phrase: str | None = None
    status_code: Any | None = None


@dataclass
class RemoveDataCollectorParameters:
    """RemoveDataCollectorParameters type type."""

    collector: Any | None = None


@dataclass
class RemoveInterceptParameters:
    """RemoveInterceptParameters type type."""

    intercept: Any | None = None


@dataclass
class SetCacheBehaviorParameters:
    """SetCacheBehaviorParameters type type."""

    cache_behavior: Any | None = None
    contexts: list[Any | None] | None = field(default_factory=list)


@dataclass
class SetExtraHeadersParameters:
    """SetExtraHeadersParameters type type."""

    headers: list[Any | None] | None = field(default_factory=list)
    contexts: list[Any | None] | None = field(default_factory=list)
    user_contexts: list[Any | None] | None = field(default_factory=list)


@dataclass
class ResponseStartedParameters:
    """ResponseStartedParameters type type."""

    response: Any | None = None


class Request:
    """Represents a network request that can be intercepted and modified."""

    def __init__(self, request_data: dict[str, Any], network_module: Any = None) -> None:
        """Initialize a Request object.
        
        Args:
            request_data: The request data from the BiDi event.
            network_module: Reference to the Network module for executing commands.
        """
        self._request_data = request_data
        self._network_module = network_module

    @property
    def url(self) -> str:
        """Get the request URL."""
        request_info = self._request_data.get("request", {})
        return request_info.get("url", "")

    @property
    def method(self) -> str:
        """Get the request method."""
        request_info = self._request_data.get("request", {})
        return request_info.get("method", "GET")

    @property
    def headers(self) -> list[Any]:
        """Get the request headers."""
        request_info = self._request_data.get("request", {})
        return request_info.get("headers", [])

    def continue_request(self, body: Any = None, cookies: list[Any] = None, headers: list[Any] = None, method: str = None, url: str = None) -> Any:
        """Continue the request with optional modifications.
        
        Args:
            body: Optional request body override.
            cookies: Optional cookies to modify.
            headers: Optional headers to modify.
            method: Optional HTTP method override.
            url: Optional URL override.
            
        Returns:
            The result of the continue_request command.
        """
        if self._network_module:
            request_id = self._request_data.get("request", {}).get("request")
            return self._network_module.continue_request(
                request=request_id,
                body=body,
                cookies=cookies,
                headers=headers,
                method=method,
                url=url
            )

    def fail_request(self) -> Any:
        """Fail the request.
        
        Returns:
            The result of the fail_request command.
        """
        if self._network_module:
            request_id = self._request_data.get("request", {}).get("request")
            return self._network_module.fail_request(request=request_id)


class Network:
    """WebDriver BiDi network module."""

    def __init__(self, driver) -> None:
        self._driver = driver
        self._request_handlers = {}  # {(phase, id): callback}
        self._auth_handlers = {}  # {id: (username, password)}
        self._handler_id_counter = 0
        self.intercepts = []  # Track active intercepts

    def add_data_collector(self, data_types: list[Any] = None, max_encoded_data_size: Any = None, collector_type: Any = None, contexts: list[Any] = None, user_contexts: list[Any] = None) -> Generator[dict, dict, dict]:
        """Execute network.addDataCollector."""
        params = {
            "dataTypes": data_types,
            "maxEncodedDataSize": max_encoded_data_size,
            "collectorType": collector_type,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.addDataCollector", params)

    def add_intercept(self, phases: list[Any] = None, contexts: list[Any] = None, url_patterns: list[Any] = None) -> Generator[dict, dict, dict]:
        """Execute network.addIntercept."""
        params = {
            "phases": phases,
            "contexts": contexts,
            "urlPatterns": url_patterns,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.addIntercept", params)

    def continue_request(self, request: Any = None, body: Any = None, cookies: list[Any] = None, headers: list[Any] = None, method: Any = None, url: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.continueRequest."""
        params = {
            "request": request,
            "body": body,
            "cookies": cookies,
            "headers": headers,
            "method": method,
            "url": url,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.continueRequest", params)

    def continue_response(self, request: Any = None, cookies: list[Any] = None, credentials: Any = None, headers: list[Any] = None, reason_phrase: Any = None, status_code: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.continueResponse."""
        params = {
            "request": request,
            "cookies": cookies,
            "credentials": credentials,
            "headers": headers,
            "reasonPhrase": reason_phrase,
            "statusCode": status_code,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.continueResponse", params)

    def continue_with_auth(self, request: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.continueWithAuth."""
        params = {
            "request": request,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.continueWithAuth", params)

    def disown_data(self, data_type: Any = None, collector: Any = None, request: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.disownData."""
        params = {
            "dataType": data_type,
            "collector": collector,
            "request": request,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.disownData", params)

    def fail_request(self, request: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.failRequest."""
        params = {
            "request": request,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.failRequest", params)

    def get_data(self, data_type: Any = None, collector: Any = None, disown: Any = None, request: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.getData."""
        params = {
            "dataType": data_type,
            "collector": collector,
            "disown": disown,
            "request": request,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.getData", params)

    def provide_response(self, request: Any = None, body: Any = None, cookies: list[Any] = None, headers: list[Any] = None, reason_phrase: Any = None, status_code: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.provideResponse."""
        params = {
            "request": request,
            "body": body,
            "cookies": cookies,
            "headers": headers,
            "reasonPhrase": reason_phrase,
            "statusCode": status_code,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.provideResponse", params)

    def remove_data_collector(self, collector: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.removeDataCollector."""
        params = {
            "collector": collector,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.removeDataCollector", params)

    def remove_intercept(self, intercept: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.removeIntercept."""
        params = {
            "intercept": intercept,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.removeIntercept", params)

    def set_cache_behavior(self, cache_behavior: Any = None, contexts: list[Any] = None) -> Generator[dict, dict, dict]:
        """Execute network.setCacheBehavior."""
        params = {
            "cacheBehavior": cache_behavior,
            "contexts": contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.setCacheBehavior", params)

    def set_extra_headers(self, headers: list[Any] = None, contexts: list[Any] = None, user_contexts: list[Any] = None) -> Generator[dict, dict, dict]:
        """Execute network.setExtraHeaders."""
        params = {
            "headers": headers,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.setExtraHeaders", params)

    def auth_required(self, response: Any = None, method: Any = None, params: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.authRequired."""
        params = {
            "response": response,
            "method": method,
            "params": params,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.authRequired", params)

    def before_request_sent(self, initiator: Any = None, method: Any = None, params: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.beforeRequestSent."""
        params = {
            "initiator": initiator,
            "method": method,
            "params": params,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.beforeRequestSent", params)

    def fetch_error(self, error_text: Any = None, method: Any = None, params: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.fetchError."""
        params = {
            "errorText": error_text,
            "method": method,
            "params": params,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.fetchError", params)

    def response_completed(self, response: Any = None, method: Any = None, params: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.responseCompleted."""
        params = {
            "response": response,
            "method": method,
            "params": params,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.responseCompleted", params)

    def response_started(self, response: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.responseStarted."""
        params = {
            "response": response,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.responseStarted", params)

    def add_request_handler(self, phase: str, callback: Any) -> int:
        """Add a handler for network requests.
        
        Args:
            phase: The phase to intercept ("before_request", "response_started", etc).
            callback: Function to call with Request object when phase is reached.
            
        Returns:
            Handler ID that can be used to remove the handler later.
        """
        self._handler_id_counter += 1
        handler_id = self._handler_id_counter
        key = (phase, handler_id)
        self._request_handlers[key] = callback
        return handler_id

    def remove_request_handler(self, phase: str, handler_id: int) -> None:
        """Remove a request handler.
        
        Args:
            phase: The phase the handler was registered for.
            handler_id: The ID returned by add_request_handler.
        """
        key = (phase, handler_id)
        if key in self._request_handlers:
            del self._request_handlers[key]

    def clear_request_handlers(self) -> None:
        """Clear all request handlers."""
        self._request_handlers.clear()

    def add_auth_handler(self, username: str, password: str) -> int:
        """Add a handler for HTTP authentication.
        
        Args:
            username: Username for authentication.
            password: Password for authentication.
            
        Returns:
            Handler ID that can be used to remove the handler later.
        """
        self._handler_id_counter += 1
        handler_id = self._handler_id_counter
        self._auth_handlers[handler_id] = (username, password)
        return handler_id

    def remove_auth_handler(self, handler_id: int) -> None:
        """Remove an auth handler.
        
        Args:
            handler_id: The ID returned by add_auth_handler.
        """
        if handler_id in self._auth_handlers:
            del self._auth_handlers[handler_id]

    def _add_intercept(self) -> dict[str, Any]:
        """Internal method to add an intercept.
        
        Returns:
            Dictionary with 'intercept' key containing the intercept ID.
        """
        # Simplified implementation for testing
        intercept_id = f"intercept_{self._handler_id_counter}"
        self._handler_id_counter += 1
        self.intercepts.append(intercept_id)
        return {"intercept": intercept_id}

    def _remove_intercept(self, intercept_id: str) -> None:
        """Internal method to remove an intercept.
        
        Args:
            intercept_id: The intercept ID to remove.
        """
        if intercept_id in self.intercepts:
            self.intercepts.remove(intercept_id)

