# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: network
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


@dataclass
class AuthCredentials:
    """AuthCredentials type type."""

    type: Optional[Any] = None
    username: Optional[str] = None
    password: Optional[str] = None


@dataclass
class StringValue:
    """StringValue type type."""

    type: Optional[Any] = None
    value: Optional[str] = None


@dataclass
class Base64Value:
    """Base64Value type type."""

    type: Optional[Any] = None
    value: Optional[str] = None


@dataclass
class Cookie:
    """Cookie type type."""

    name: Optional[str] = None
    value: Optional[Any] = None
    domain: Optional[str] = None
    path: Optional[str] = None
    size: Optional[Any] = None
    http_only: Optional[bool] = None
    secure: Optional[bool] = None
    same_site: Optional[Any] = None
    expiry: Optional[Any] = None


@dataclass
class CookieHeader:
    """CookieHeader type type."""

    name: Optional[str] = None
    value: Optional[Any] = None


@dataclass
class Header:
    """Header type type."""

    name: Optional[str] = None
    value: Optional[Any] = None


@dataclass
class SetCookieHeader:
    """SetCookieHeader type type."""

    name: Optional[str] = None
    value: Optional[Any] = None
    domain: Optional[str] = None
    http_only: Optional[bool] = None
    expiry: Optional[str] = None
    max_age: Optional[Any] = None
    path: Optional[str] = None
    same_site: Optional[Any] = None
    secure: Optional[bool] = None


@dataclass
class UrlPatternPattern:
    """UrlPatternPattern type type."""

    type: Optional[Any] = None
    protocol: Optional[str] = None
    hostname: Optional[str] = None
    port: Optional[str] = None
    pathname: Optional[str] = None
    search: Optional[str] = None


@dataclass
class UrlPatternString:
    """UrlPatternString type type."""

    type: Optional[Any] = None
    pattern: Optional[str] = None


@dataclass
class AddDataCollectorParameters:
    """AddDataCollectorParameters type type."""

    data_types: Optional[List[Optional[Any]]] = field(default_factory=list)
    max_encoded_data_size: Optional[Any] = None
    collector_type: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class AddInterceptParameters:
    """AddInterceptParameters type type."""

    phases: Optional[List[Optional[Any]]] = field(default_factory=list)
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    url_patterns: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class ContinueResponseParameters:
    """ContinueResponseParameters type type."""

    request: Optional[Any] = None
    cookies: Optional[List[Optional[Any]]] = field(default_factory=list)
    credentials: Optional[Any] = None
    headers: Optional[List[Optional[Any]]] = field(default_factory=list)
    reason_phrase: Optional[str] = None
    status_code: Optional[Any] = None


@dataclass
class ContinueWithAuthParameters:
    """ContinueWithAuthParameters type type."""

    request: Optional[Any] = None


@dataclass
class ContinueWithAuthCredentials:
    """ContinueWithAuthCredentials type type."""

    action: Optional[Any] = None
    credentials: Optional[Any] = None


@dataclass
class ContinueWithAuthNoCredentials:
    """ContinueWithAuthNoCredentials type type."""

    action: Optional[Any] = None


@dataclass
class disownDataParameters:
    """disownDataParameters type type."""

    data_type: Optional[Any] = None
    collector: Optional[Any] = None
    request: Optional[Any] = None


@dataclass
class FailRequestParameters:
    """FailRequestParameters type type."""

    request: Optional[Any] = None


@dataclass
class GetDataParameters:
    """GetDataParameters type type."""

    data_type: Optional[Any] = None
    collector: Optional[Any] = None
    disown: Optional[Any] = None
    request: Optional[Any] = None


@dataclass
class ProvideResponseParameters:
    """ProvideResponseParameters type type."""

    request: Optional[Any] = None
    body: Optional[Any] = None
    cookies: Optional[List[Optional[Any]]] = field(default_factory=list)
    headers: Optional[List[Optional[Any]]] = field(default_factory=list)
    reason_phrase: Optional[str] = None
    status_code: Optional[Any] = None


@dataclass
class RemoveDataCollectorParameters:
    """RemoveDataCollectorParameters type type."""

    collector: Optional[Any] = None


@dataclass
class RemoveInterceptParameters:
    """RemoveInterceptParameters type type."""

    intercept: Optional[Any] = None


@dataclass
class SetCacheBehaviorParameters:
    """SetCacheBehaviorParameters type type."""

    cache_behavior: Optional[Any] = None
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class SetExtraHeadersParameters:
    """SetExtraHeadersParameters type type."""

    headers: Optional[List[Optional[Any]]] = field(default_factory=list)
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


class Network:
    """WebDriver BiDi network module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def add_data_collector(self, data_types: List[Any] = None, max_encoded_data_size: Any = None, collector_type: Any = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute network.addDataCollector."""
        params = {
            "dataTypes": data_types,
            "maxEncodedDataSize": max_encoded_data_size,
            "collectorType": collector_type,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.addDataCollector", params)

    def add_intercept(self, phases: List[Any] = None, contexts: List[Any] = None, url_patterns: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute network.addIntercept."""
        params = {
            "phases": phases,
            "contexts": contexts,
            "urlPatterns": url_patterns,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.addIntercept", params)

    def continue_request(self, request: Any = None, body: Any = None, cookies: List[Any] = None, headers: List[Any] = None, method: Any = None, url: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.continueRequest."""
        params = {
            "request": request,
            "body": body,
            "cookies": cookies,
            "headers": headers,
            "method": method,
            "url": url,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.continueRequest", params)

    def continue_response(self, request: Any = None, cookies: List[Any] = None, credentials: Any = None, headers: List[Any] = None, reason_phrase: Any = None, status_code: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.continueResponse."""
        params = {
            "request": request,
            "cookies": cookies,
            "credentials": credentials,
            "headers": headers,
            "reasonPhrase": reason_phrase,
            "statusCode": status_code,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.continueResponse", params)

    def continue_with_auth(self, request: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.continueWithAuth."""
        params = {
            "request": request,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.continueWithAuth", params)

    def disown_data(self, data_type: Any = None, collector: Any = None, request: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.disownData."""
        params = {
            "dataType": data_type,
            "collector": collector,
            "request": request,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.disownData", params)

    def fail_request(self, request: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.failRequest."""
        params = {
            "request": request,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.failRequest", params)

    def get_data(self, data_type: Any = None, collector: Any = None, disown: Any = None, request: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.getData."""
        params = {
            "dataType": data_type,
            "collector": collector,
            "disown": disown,
            "request": request,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.getData", params)

    def provide_response(self, request: Any = None, body: Any = None, cookies: List[Any] = None, headers: List[Any] = None, reason_phrase: Any = None, status_code: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.provideResponse."""
        params = {
            "request": request,
            "body": body,
            "cookies": cookies,
            "headers": headers,
            "reasonPhrase": reason_phrase,
            "statusCode": status_code,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.provideResponse", params)

    def remove_data_collector(self, collector: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.removeDataCollector."""
        params = {
            "collector": collector,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.removeDataCollector", params)

    def remove_intercept(self, intercept: Any = None) -> Generator[dict, dict, dict]:
        """Execute network.removeIntercept."""
        params = {
            "intercept": intercept,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.removeIntercept", params)

    def set_cache_behavior(self, cache_behavior: Any = None, contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute network.setCacheBehavior."""
        params = {
            "cacheBehavior": cache_behavior,
            "contexts": contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.setCacheBehavior", params)

    def set_extra_headers(self, headers: List[Any] = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute network.setExtraHeaders."""
        params = {
            "headers": headers,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("network.setExtraHeaders", params)

