# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: script
from __future__ import annotations

from typing import Any
from .common import command_builder
from dataclasses import field
from typing import Any
from dataclasses import dataclass


class RealmType:
    """Realm type enum."""

    WINDOW = "window"
    WORKER = "worker"
    PAINT_WORKLET = "paint_worklet"
    AUDIO_WORKLET = "audio_worklet"
    WORKLET = "worklet"
    SHARED_WORKER = "shared_worker"
    SERVICE_WORKER = "service_worker"
    DEDICATED_WORKER = "dedicated_worker"


class ResultOwnership:
    """Result ownership enum."""

    ROOT = "root"
    NONE = "none"


@dataclass
class ChannelValue:
    """ChannelValue type type."""

    type: Any | None = None
    value: Any | None = None


@dataclass
class ChannelProperties:
    """ChannelProperties type type."""

    channel: Any | None = None
    serialization_options: Any | None = None
    ownership: Any | None = None


@dataclass
class EvaluateResultSuccess:
    """EvaluateResultSuccess type type."""

    type: Any | None = None
    result: Any | None = None
    realm: Any | None = None


@dataclass
class EvaluateResultException:
    """EvaluateResultException type type."""

    type: Any | None = None
    exception_details: Any | None = None
    realm: Any | None = None


@dataclass
class ExceptionDetails:
    """ExceptionDetails type type."""

    column_number: Any | None = None
    exception: Any | None = None
    line_number: Any | None = None
    stack_trace: Any | None = None
    text: str | None = None


@dataclass
class ArrayLocalValue:
    """ArrayLocalValue type type."""

    type: Any | None = None
    value: Any | None = None


@dataclass
class DateLocalValue:
    """DateLocalValue type type."""

    type: Any | None = None
    value: str | None = None


@dataclass
class MapLocalValue:
    """MapLocalValue type type."""

    type: Any | None = None
    value: Any | None = None


@dataclass
class ObjectLocalValue:
    """ObjectLocalValue type type."""

    type: Any | None = None
    value: Any | None = None


@dataclass
class RegExpValue:
    """RegExpValue type type."""

    pattern: str | None = None
    flags: str | None = None


@dataclass
class RegExpLocalValue:
    """RegExpLocalValue type type."""

    type: Any | None = None
    value: Any | None = None


@dataclass
class SetLocalValue:
    """SetLocalValue type type."""

    type: Any | None = None
    value: Any | None = None


@dataclass
class UndefinedValue:
    """UndefinedValue type type."""

    type: Any | None = None


@dataclass
class NullValue:
    """NullValue type type."""

    type: Any | None = None


@dataclass
class StringValue:
    """StringValue type type."""

    type: Any | None = None
    value: str | None = None


@dataclass
class NumberValue:
    """NumberValue type type."""

    type: Any | None = None
    value: Any | None = None


@dataclass
class BooleanValue:
    """BooleanValue type type."""

    type: Any | None = None
    value: bool | None = None


@dataclass
class BigIntValue:
    """BigIntValue type type."""

    type: Any | None = None
    value: str | None = None


@dataclass
class BaseRealmInfo:
    """BaseRealmInfo type type."""

    realm: Any | None = None
    origin: str | None = None


@dataclass
class WindowRealmInfo:
    """WindowRealmInfo type type."""

    type: Any | None = None
    context: Any | None = None
    sandbox: str | None = None


@dataclass
class DedicatedWorkerRealmInfo:
    """DedicatedWorkerRealmInfo type type."""

    type: Any | None = None
    owners: list[Any | None] | None = field(default_factory=list)


@dataclass
class SharedWorkerRealmInfo:
    """SharedWorkerRealmInfo type type."""

    type: Any | None = None


@dataclass
class ServiceWorkerRealmInfo:
    """ServiceWorkerRealmInfo type type."""

    type: Any | None = None


@dataclass
class WorkerRealmInfo:
    """WorkerRealmInfo type type."""

    type: Any | None = None


@dataclass
class PaintWorkletRealmInfo:
    """PaintWorkletRealmInfo type type."""

    type: Any | None = None


@dataclass
class AudioWorkletRealmInfo:
    """AudioWorkletRealmInfo type type."""

    type: Any | None = None


@dataclass
class WorkletRealmInfo:
    """WorkletRealmInfo type type."""

    type: Any | None = None


@dataclass
class SharedReference:
    """SharedReference type type."""

    shared_id: Any | None = None
    handle: Any | None = None


@dataclass
class RemoteObjectReference:
    """RemoteObjectReference type type."""

    handle: Any | None = None
    shared_id: Any | None = None


@dataclass
class SymbolRemoteValue:
    """SymbolRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class ArrayRemoteValue:
    """ArrayRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None
    value: Any | None = None


@dataclass
class ObjectRemoteValue:
    """ObjectRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None
    value: Any | None = None


@dataclass
class FunctionRemoteValue:
    """FunctionRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class RegExpRemoteValue:
    """RegExpRemoteValue type type."""

    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class DateRemoteValue:
    """DateRemoteValue type type."""

    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class MapRemoteValue:
    """MapRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None
    value: Any | None = None


@dataclass
class SetRemoteValue:
    """SetRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None
    value: Any | None = None


@dataclass
class WeakMapRemoteValue:
    """WeakMapRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class WeakSetRemoteValue:
    """WeakSetRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class GeneratorRemoteValue:
    """GeneratorRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class ErrorRemoteValue:
    """ErrorRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class ProxyRemoteValue:
    """ProxyRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class PromiseRemoteValue:
    """PromiseRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class TypedArrayRemoteValue:
    """TypedArrayRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class ArrayBufferRemoteValue:
    """ArrayBufferRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class NodeListRemoteValue:
    """NodeListRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None
    value: Any | None = None


@dataclass
class HTMLCollectionRemoteValue:
    """HTMLCollectionRemoteValue type type."""

    type: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None
    value: Any | None = None


@dataclass
class NodeRemoteValue:
    """NodeRemoteValue type type."""

    type: Any | None = None
    shared_id: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None
    value: Any | None = None


@dataclass
class NodeProperties:
    """NodeProperties type type."""

    node_type: Any | None = None
    child_node_count: Any | None = None
    children: list[Any | None] | None = field(default_factory=list)
    local_name: str | None = None
    mode: Any | None = None
    namespace_uri: str | None = None
    node_value: str | None = None
    shadow_root: Any | None = None


@dataclass
class WindowProxyRemoteValue:
    """WindowProxyRemoteValue type type."""

    type: Any | None = None
    value: Any | None = None
    handle: Any | None = None
    internal_id: Any | None = None


@dataclass
class WindowProxyProperties:
    """WindowProxyProperties type type."""

    context: Any | None = None


@dataclass
class StackFrame:
    """StackFrame type type."""

    column_number: Any | None = None
    function_name: str | None = None
    line_number: Any | None = None
    url: str | None = None


@dataclass
class StackTrace:
    """StackTrace type type."""

    call_frames: list[Any | None] | None = field(default_factory=list)


@dataclass
class Source:
    """Source type type."""

    realm: Any | None = None
    context: Any | None = None


@dataclass
class RealmTarget:
    """RealmTarget type type."""

    realm: Any | None = None


@dataclass
class ContextTarget:
    """ContextTarget type type."""

    context: Any | None = None
    sandbox: str | None = None


@dataclass
class AddPreloadScriptParameters:
    """AddPreloadScriptParameters type type."""

    function_declaration: str | None = None
    arguments: list[Any | None] | None = field(default_factory=list)
    contexts: list[Any | None] | None = field(default_factory=list)
    user_contexts: list[Any | None] | None = field(default_factory=list)
    sandbox: str | None = None


@dataclass
class AddPreloadScriptResult:
    """AddPreloadScriptResult type type."""

    script: Any | None = None


@dataclass
class DisownParameters:
    """DisownParameters type type."""

    handles: list[Any | None] | None = field(default_factory=list)
    target: Any | None = None


@dataclass
class CallFunctionParameters:
    """CallFunctionParameters type type."""

    function_declaration: str | None = None
    await_promise: bool | None = None
    target: Any | None = None
    arguments: list[Any | None] | None = field(default_factory=list)
    result_ownership: Any | None = None
    serialization_options: Any | None = None
    this: Any | None = None
    user_activation: Any | None = None


@dataclass
class EvaluateParameters:
    """EvaluateParameters type type."""

    expression: str | None = None
    target: Any | None = None
    await_promise: bool | None = None
    result_ownership: Any | None = None
    serialization_options: Any | None = None
    user_activation: Any | None = None


@dataclass
class GetRealmsParameters:
    """GetRealmsParameters type type."""

    context: Any | None = None
    type: Any | None = None


@dataclass
class GetRealmsResult:
    """GetRealmsResult type type."""

    realms: list[Any | None] | None = field(default_factory=list)


@dataclass
class RemovePreloadScriptParameters:
    """RemovePreloadScriptParameters type type."""

    script: Any | None = None


@dataclass
class MessageParameters:
    """MessageParameters type type."""

    channel: Any | None = None
    data: Any | None = None
    source: Any | None = None


@dataclass
class RealmDestroyedParameters:
    """RealmDestroyedParameters type type."""

    realm: Any | None = None


class Script:
    """WebDriver BiDi script module."""

    def __init__(self, driver) -> None:
        self._driver = driver
        self._console_handlers = {}  # {id: callback}
        self._js_error_handlers = {}  # {id: callback}
        self._handler_id_counter = 0
        self._subscribed_to_logs = False

    def add_preload_script(
        self,
        function_declaration: Any = None,
        arguments: list[Any] = None,
        contexts: list[Any] = None,
        user_contexts: list[Any] = None,
        sandbox: Any = None,
    ) -> Generator[dict, dict, dict]:
        """Execute script.addPreloadScript."""
        params = {
            "functionDeclaration": function_declaration,
            "arguments": arguments,
            "contexts": contexts,
            "userContexts": user_contexts,
            "sandbox": sandbox,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.addPreloadScript", params)

    def disown(
        self, handles: list[Any] = None, target: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute script.disown."""
        params = {
            "handles": handles,
            "target": target,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.disown", params)

    def call_function(
        self,
        function_declaration: Any = None,
        await_promise: bool = None,
        target: Any = None,
        arguments: list[Any] = None,
        result_ownership: Any = None,
        serialization_options: Any = None,
        this: Any = None,
        user_activation: Any = None,
    ) -> Generator[dict, dict, dict]:
        """Execute script.callFunction."""
        params = {
            "functionDeclaration": function_declaration,
            "awaitPromise": await_promise,
            "target": target,
            "arguments": arguments,
            "resultOwnership": result_ownership,
            "serializationOptions": serialization_options,
            "this": this,
            "userActivation": user_activation,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.callFunction", params)

    def evaluate(
        self,
        expression: Any = None,
        target: Any = None,
        await_promise: bool = None,
        result_ownership: Any = None,
        serialization_options: Any = None,
        user_activation: Any = None,
    ) -> Generator[dict, dict, dict]:
        """Execute script.evaluate."""
        params = {
            "expression": expression,
            "target": target,
            "awaitPromise": await_promise,
            "resultOwnership": result_ownership,
            "serializationOptions": serialization_options,
            "userActivation": user_activation,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.evaluate", params)

    def get_realms(
        self, context: Any = None, type: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute script.getRealms."""
        params = {
            "context": context,
            "type": type,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.getRealms", params)

    def remove_preload_script(self, script: Any = None) -> Generator[dict, dict, dict]:
        """Execute script.removePreloadScript."""
        params = {
            "script": script,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.removePreloadScript", params)

    def message(
        self, channel: Any = None, data: Any = None, source: Any = None
    ) -> Generator[dict, dict, dict]:
        """Execute script.message."""
        params = {
            "channel": channel,
            "data": data,
            "source": source,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.message", params)

    def realm_created(self) -> Generator[dict, dict, dict]:
        """Execute script.realmCreated."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.realmCreated", params)

    def realm_destroyed(self, realm: Any = None) -> Generator[dict, dict, dict]:
        """Execute script.realmDestroyed."""
        params = {
            "realm": realm,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.realmDestroyed", params)

    def add_console_message_handler(self, callback: Any) -> int:
        """Add a handler for console messages.

        Args:
            callback: Function to call with log entry when console message is logged.

        Returns:
            Handler ID that can be used to remove the handler later.
        """
        self._handler_id_counter += 1
        handler_id = self._handler_id_counter
        self._console_handlers[handler_id] = callback
        self._subscribe_to_logs()
        return handler_id

    def remove_console_message_handler(self, handler_id: int) -> None:
        """Remove a console message handler.

        Args:
            handler_id: The ID returned by add_console_message_handler.
        """
        if handler_id in self._console_handlers:
            del self._console_handlers[handler_id]

    def add_javascript_error_handler(self, callback: Any) -> int:
        """Add a handler for JavaScript errors.

        Args:
            callback: Function to call with log entry when JS error occurs.

        Returns:
            Handler ID that can be used to remove the handler later.
        """
        self._handler_id_counter += 1
        handler_id = self._handler_id_counter
        self._js_error_handlers[handler_id] = callback
        self._subscribe_to_logs()
        return handler_id

    def remove_javascript_error_handler(self, handler_id: int) -> None:
        """Remove a JavaScript error handler.

        Args:
            handler_id: The ID returned by add_javascript_error_handler.
        """
        if handler_id in self._js_error_handlers:
            del self._js_error_handlers[handler_id]

    def _subscribe_to_logs(self) -> None:
        """Subscribe to log events if not already subscribed."""
        if self._subscribed_to_logs:
            return
        self._subscribed_to_logs = True

    def _add_preload_script(
        self,
        function_declaration: Any = None,
        arguments: list[Any] = None,
        contexts: list[Any] = None,
        user_contexts: list[Any] = None,
        sandbox: Any = None,
    ) -> Any:
        """Internal method to add preload script."""
        return self.add_preload_script(
            function_declaration=function_declaration,
            arguments=arguments,
            contexts=contexts,
            user_contexts=user_contexts,
            sandbox=sandbox,
        )

    def _remove_preload_script(self, script_id: Any = None) -> Any:
        """Internal method to remove preload script."""
        return self.remove_preload_script(script=script_id)

    def _evaluate(
        self,
        expression: Any = None,
        target: Any = None,
        await_promise: bool = None,
        result_ownership: Any = None,
        serialization_options: Any = None,
        user_activation: Any = None,
    ) -> Any:
        """Internal method to evaluate expression."""
        return self.evaluate(
            expression=expression,
            target=target,
            await_promise=await_promise,
            result_ownership=result_ownership,
            serialization_options=serialization_options,
            user_activation=user_activation,
        )

    def _get_realms(self, context: Any = None, type: Any = None) -> Any:
        """Internal method to get realms."""
        return self.get_realms(context=context, type=type)

    def _disown(self, handles: list[Any] = None, target: Any = None) -> Any:
        """Internal method to disown handles."""
        return self.disown(handles=handles, target=target)
