# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: script
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


@dataclass
class ChannelValue:
    """ChannelValue type type."""

    type: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class ChannelProperties:
    """ChannelProperties type type."""

    channel: Optional[Any] = None
    serialization_options: Optional[Any] = None
    ownership: Optional[Any] = None


@dataclass
class EvaluateResultSuccess:
    """EvaluateResultSuccess type type."""

    type: Optional[Any] = None
    result: Optional[Any] = None
    realm: Optional[Any] = None


@dataclass
class EvaluateResultException:
    """EvaluateResultException type type."""

    type: Optional[Any] = None
    exception_details: Optional[Any] = None
    realm: Optional[Any] = None


@dataclass
class ExceptionDetails:
    """ExceptionDetails type type."""

    column_number: Optional[Any] = None
    exception: Optional[Any] = None
    line_number: Optional[Any] = None
    stack_trace: Optional[Any] = None
    text: Optional[str] = None


@dataclass
class ArrayLocalValue:
    """ArrayLocalValue type type."""

    type: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class DateLocalValue:
    """DateLocalValue type type."""

    type: Optional[Any] = None
    value: Optional[str] = None


@dataclass
class MapLocalValue:
    """MapLocalValue type type."""

    type: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class ObjectLocalValue:
    """ObjectLocalValue type type."""

    type: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class RegExpValue:
    """RegExpValue type type."""

    pattern: Optional[str] = None
    flags: Optional[str] = None


@dataclass
class RegExpLocalValue:
    """RegExpLocalValue type type."""

    type: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class SetLocalValue:
    """SetLocalValue type type."""

    type: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class UndefinedValue:
    """UndefinedValue type type."""

    type: Optional[Any] = None


@dataclass
class NullValue:
    """NullValue type type."""

    type: Optional[Any] = None


@dataclass
class StringValue:
    """StringValue type type."""

    type: Optional[Any] = None
    value: Optional[str] = None


@dataclass
class NumberValue:
    """NumberValue type type."""

    type: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class BooleanValue:
    """BooleanValue type type."""

    type: Optional[Any] = None
    value: Optional[bool] = None


@dataclass
class BigIntValue:
    """BigIntValue type type."""

    type: Optional[Any] = None
    value: Optional[str] = None


@dataclass
class SharedReference:
    """SharedReference type type."""

    shared_id: Optional[Any] = None
    handle: Optional[Any] = None


@dataclass
class RemoteObjectReference:
    """RemoteObjectReference type type."""

    handle: Optional[Any] = None
    shared_id: Optional[Any] = None


@dataclass
class SymbolRemoteValue:
    """SymbolRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class ArrayRemoteValue:
    """ArrayRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class ObjectRemoteValue:
    """ObjectRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class FunctionRemoteValue:
    """FunctionRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class RegExpRemoteValue:
    """RegExpRemoteValue type type."""

    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class DateRemoteValue:
    """DateRemoteValue type type."""

    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class MapRemoteValue:
    """MapRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class SetRemoteValue:
    """SetRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class WeakMapRemoteValue:
    """WeakMapRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class WeakSetRemoteValue:
    """WeakSetRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class GeneratorRemoteValue:
    """GeneratorRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class ErrorRemoteValue:
    """ErrorRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class ProxyRemoteValue:
    """ProxyRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class PromiseRemoteValue:
    """PromiseRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class TypedArrayRemoteValue:
    """TypedArrayRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class ArrayBufferRemoteValue:
    """ArrayBufferRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class NodeListRemoteValue:
    """NodeListRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class HTMLCollectionRemoteValue:
    """HTMLCollectionRemoteValue type type."""

    type: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class NodeRemoteValue:
    """NodeRemoteValue type type."""

    type: Optional[Any] = None
    shared_id: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None
    value: Optional[Any] = None


@dataclass
class NodeProperties:
    """NodeProperties type type."""

    node_type: Optional[Any] = None
    child_node_count: Optional[Any] = None
    children: Optional[List[Optional[Any]]] = field(default_factory=list)
    local_name: Optional[str] = None
    mode: Optional[Any] = None
    namespace_uri: Optional[str] = None
    node_value: Optional[str] = None
    shadow_root: Optional[Any] = None


@dataclass
class WindowProxyRemoteValue:
    """WindowProxyRemoteValue type type."""

    type: Optional[Any] = None
    value: Optional[Any] = None
    handle: Optional[Any] = None
    internal_id: Optional[Any] = None


@dataclass
class WindowProxyProperties:
    """WindowProxyProperties type type."""

    context: Optional[Any] = None


@dataclass
class StackFrame:
    """StackFrame type type."""

    column_number: Optional[Any] = None
    function_name: Optional[str] = None
    line_number: Optional[Any] = None
    url: Optional[str] = None


@dataclass
class StackTrace:
    """StackTrace type type."""

    call_frames: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class RealmTarget:
    """RealmTarget type type."""

    realm: Optional[Any] = None


@dataclass
class ContextTarget:
    """ContextTarget type type."""

    context: Optional[Any] = None
    sandbox: Optional[str] = None


@dataclass
class AddPreloadScriptParameters:
    """AddPreloadScriptParameters type type."""

    function_declaration: Optional[str] = None
    arguments: Optional[List[Optional[Any]]] = field(default_factory=list)
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    sandbox: Optional[str] = None


@dataclass
class DisownParameters:
    """DisownParameters type type."""

    handles: Optional[List[Optional[Any]]] = field(default_factory=list)
    target: Optional[Any] = None


@dataclass
class CallFunctionParameters:
    """CallFunctionParameters type type."""

    function_declaration: Optional[str] = None
    await_promise: Optional[bool] = None
    target: Optional[Any] = None
    arguments: Optional[List[Optional[Any]]] = field(default_factory=list)
    result_ownership: Optional[Any] = None
    serialization_options: Optional[Any] = None
    this: Optional[Any] = None
    user_activation: Optional[Any] = None


@dataclass
class EvaluateParameters:
    """EvaluateParameters type type."""

    expression: Optional[str] = None
    target: Optional[Any] = None
    await_promise: Optional[bool] = None
    result_ownership: Optional[Any] = None
    serialization_options: Optional[Any] = None
    user_activation: Optional[Any] = None


@dataclass
class GetRealmsParameters:
    """GetRealmsParameters type type."""

    context: Optional[Any] = None
    type: Optional[Any] = None


@dataclass
class RemovePreloadScriptParameters:
    """RemovePreloadScriptParameters type type."""

    script: Optional[Any] = None


class Script:
    """WebDriver BiDi script module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def add_preload_script(self, function_declaration: Any = None, arguments: List[Any] = None, contexts: List[Any] = None, user_contexts: List[Any] = None, sandbox: Any = None) -> Generator[dict, dict, dict]:
        """Execute script.addPreloadScript."""
        params = {
            "functionDeclaration": function_declaration,
            "arguments": arguments,
            "contexts": contexts,
            "userContexts": user_contexts,
            "sandbox": sandbox,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.addPreloadScript", params)

    def disown(self, handles: List[Any] = None, target: Any = None) -> Generator[dict, dict, dict]:
        """Execute script.disown."""
        params = {
            "handles": handles,
            "target": target,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.disown", params)

    def call_function(self, function_declaration: Any = None, await_promise: bool = None, target: Any = None, arguments: List[Any] = None, result_ownership: Any = None, serialization_options: Any = None, this: Any = None, user_activation: Any = None) -> Generator[dict, dict, dict]:
        """Execute script.callFunction."""
        params = {
            "functionDeclaration": function_declaration,
            "awaitPromise": await_promise,
            "target": target,
            "arguments": arguments,
            "resultOwnership": result_ownership,
            "serializationOptions": serialization_options,
            "this": this,
            "userActivation": user_activation,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.callFunction", params)

    def evaluate(self, expression: Any = None, target: Any = None, await_promise: bool = None, result_ownership: Any = None, serialization_options: Any = None, user_activation: Any = None) -> Generator[dict, dict, dict]:
        """Execute script.evaluate."""
        params = {
            "expression": expression,
            "target": target,
            "awaitPromise": await_promise,
            "resultOwnership": result_ownership,
            "serializationOptions": serialization_options,
            "userActivation": user_activation,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.evaluate", params)

    def get_realms(self, context: Any = None, type: Any = None) -> Generator[dict, dict, dict]:
        """Execute script.getRealms."""
        params = {
            "context": context,
            "type": type,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.getRealms", params)

    def remove_preload_script(self, script: Any = None) -> Generator[dict, dict, dict]:
        """Execute script.removePreloadScript."""
        params = {
            "script": script,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("script.removePreloadScript", params)

