# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: session
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


@dataclass
class CapabilitiesRequest:
    """CapabilitiesRequest type type."""

    always_match: Optional[Any] = None
    first_match: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class CapabilityRequest:
    """CapabilityRequest type type."""

    accept_insecure_certs: Optional[bool] = None
    browser_name: Optional[str] = None
    browser_version: Optional[str] = None
    platform_name: Optional[str] = None
    proxy: Optional[Any] = None
    unhandled_prompt_behavior: Optional[Any] = None


@dataclass
class AutodetectProxyConfiguration:
    """AutodetectProxyConfiguration type type."""

    proxy_type: Optional[Any] = None


@dataclass
class DirectProxyConfiguration:
    """DirectProxyConfiguration type type."""

    proxy_type: Optional[Any] = None


@dataclass
class ManualProxyConfiguration:
    """ManualProxyConfiguration type type."""

    proxy_type: Optional[Any] = None
    http_proxy: Optional[str] = None
    ssl_proxy: Optional[str] = None
    no_proxy: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class SocksProxyConfiguration:
    """SocksProxyConfiguration type type."""

    socks_proxy: Optional[str] = None
    socks_version: Optional[Any] = None


@dataclass
class PacProxyConfiguration:
    """PacProxyConfiguration type type."""

    proxy_type: Optional[Any] = None
    proxy_autoconfig_url: Optional[str] = None


@dataclass
class SystemProxyConfiguration:
    """SystemProxyConfiguration type type."""

    proxy_type: Optional[Any] = None


@dataclass
class UserPromptHandler:
    """UserPromptHandler type type."""

    alert: Optional[Any] = None
    before_unload: Optional[Any] = None
    confirm: Optional[Any] = None
    default: Optional[Any] = None
    file: Optional[Any] = None
    prompt: Optional[Any] = None


@dataclass
class SubscribeParameters:
    """SubscribeParameters type type."""

    events: Optional[List[Optional[str]]] = field(default_factory=list)
    contexts: Optional[List[Optional[Any]]] = field(default_factory=list)
    user_contexts: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class UnsubscribeByIDRequest:
    """UnsubscribeByIDRequest type type."""

    subscriptions: Optional[List[Optional[Any]]] = field(default_factory=list)


@dataclass
class UnsubscribeByAttributesRequest:
    """UnsubscribeByAttributesRequest type type."""

    events: Optional[List[Optional[str]]] = field(default_factory=list)


@dataclass
class NewParameters:
    """NewParameters type type."""

    capabilities: Optional[Any] = None


class Session:
    """WebDriver BiDi session module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def status(self) -> Generator[dict, dict, dict]:
        """Execute session.status."""
        params = {
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("session.status", params)

    def new(self, capabilities: Any = None) -> Generator[dict, dict, dict]:
        """Execute session.new."""
        params = {
            "capabilities": capabilities,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("session.new", params)

    def end(self) -> Generator[dict, dict, dict]:
        """Execute session.end."""
        params = {
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("session.end", params)

    def subscribe(self, events: List[Any] = None, contexts: List[Any] = None, user_contexts: List[Any] = None) -> Generator[dict, dict, dict]:
        """Execute session.subscribe."""
        params = {
            "events": events,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("session.subscribe", params)

    def unsubscribe(self) -> Generator[dict, dict, dict]:
        """Execute session.unsubscribe."""
        params = {
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("session.unsubscribe", params)

