# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: session
from __future__ import annotations

from typing import Any
from .common import command_builder
from dataclasses import field
from typing import Any
from dataclasses import dataclass


class UserPromptHandlerType:
    """UserPromptHandlerType enum."""

    DISMISS = "dismiss"
    ACCEPT = "accept"
    REPORT_JAVASCRIPT_ERROR = "report-javascript-error"
    REPORT_ERROR = "report-error"


class UserPromptHandler:
    """UserPromptHandler type."""

    pass


@dataclass
class CapabilitiesRequest:
    """CapabilitiesRequest type type."""

    always_match: Any | None = None
    first_match: list[Any | None] | None = field(default_factory=list)


@dataclass
class CapabilityRequest:
    """CapabilityRequest type type."""

    accept_insecure_certs: bool | None = None
    browser_name: str | None = None
    browser_version: str | None = None
    platform_name: str | None = None
    proxy: Any | None = None
    unhandled_prompt_behavior: Any | None = None


@dataclass
class AutodetectProxyConfiguration:
    """AutodetectProxyConfiguration type type."""

    proxy_type: Any | None = None


@dataclass
class DirectProxyConfiguration:
    """DirectProxyConfiguration type type."""

    proxy_type: Any | None = None


@dataclass
class ManualProxyConfiguration:
    """ManualProxyConfiguration type type."""

    proxy_type: Any | None = None
    http_proxy: str | None = None
    ssl_proxy: str | None = None
    no_proxy: list[Any | None] | None = field(default_factory=list)


@dataclass
class SocksProxyConfiguration:
    """SocksProxyConfiguration type type."""

    socks_proxy: str | None = None
    socks_version: Any | None = None


@dataclass
class PacProxyConfiguration:
    """PacProxyConfiguration type type."""

    proxy_type: Any | None = None
    proxy_autoconfig_url: str | None = None


@dataclass
class SystemProxyConfiguration:
    """SystemProxyConfiguration type type."""

    proxy_type: Any | None = None


@dataclass
class UserPromptHandler:
    """UserPromptHandler type type."""

    alert: Any | None = None
    before_unload: Any | None = None
    confirm: Any | None = None
    default: Any | None = None
    file: Any | None = None
    prompt: Any | None = None


@dataclass
class SubscribeParameters:
    """SubscribeParameters type type."""

    events: list[str | None] | None = field(default_factory=list)
    contexts: list[Any | None] | None = field(default_factory=list)
    user_contexts: list[Any | None] | None = field(default_factory=list)


@dataclass
class UnsubscribeByIDRequest:
    """UnsubscribeByIDRequest type type."""

    subscriptions: list[Any | None] | None = field(default_factory=list)


@dataclass
class UnsubscribeByAttributesRequest:
    """UnsubscribeByAttributesRequest type type."""

    events: list[str | None] | None = field(default_factory=list)


@dataclass
class StatusResult:
    """StatusResult type type."""

    ready: bool | None = None
    message: str | None = None


@dataclass
class NewParameters:
    """NewParameters type type."""

    capabilities: Any | None = None


@dataclass
class NewResult:
    """NewResult type type."""

    session_id: str | None = None
    accept_insecure_certs: bool | None = None
    browser_name: str | None = None
    browser_version: str | None = None
    platform_name: str | None = None
    set_window_rect: bool | None = None
    user_agent: str | None = None
    proxy: Any | None = None
    unhandled_prompt_behavior: Any | None = None
    web_socket_url: str | None = None


@dataclass
class SubscribeResult:
    """SubscribeResult type type."""

    subscription: Any | None = None


class Session:
    """WebDriver BiDi session module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def status(self) -> Generator[dict, dict, dict]:
        """Execute session.status."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("session.status", params)

    def new(self, capabilities: Any = None) -> Generator[dict, dict, dict]:
        """Execute session.new."""
        params = {
            "capabilities": capabilities,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("session.new", params)

    def end(self) -> Generator[dict, dict, dict]:
        """Execute session.end."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("session.end", params)

    def subscribe(
        self,
        events: list[Any] = None,
        contexts: list[Any] = None,
        user_contexts: list[Any] = None,
    ) -> Generator[dict, dict, dict]:
        """Execute session.subscribe."""
        params = {
            "events": events,
            "contexts": contexts,
            "userContexts": user_contexts,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("session.subscribe", params)

    def unsubscribe(self) -> Generator[dict, dict, dict]:
        """Execute session.unsubscribe."""
        params = {}
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("session.unsubscribe", params)
