# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: storage
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


@dataclass
class PartitionKey:
    """PartitionKey type type."""

    user_context: Optional[str] = None
    source_origin: Optional[str] = None


@dataclass
class CookieFilter:
    """CookieFilter type type."""

    name: Optional[str] = None
    value: Optional[Any] = None
    domain: Optional[str] = None
    path: Optional[str] = None
    size: Optional[Any] = None
    http_only: Optional[bool] = None
    secure: Optional[bool] = None
    same_site: Optional[Any] = None
    expiry: Optional[Any] = None


@dataclass
class BrowsingContextPartitionDescriptor:
    """BrowsingContextPartitionDescriptor type type."""

    type: Optional[Any] = None
    context: Optional[Any] = None


@dataclass
class StorageKeyPartitionDescriptor:
    """StorageKeyPartitionDescriptor type type."""

    type: Optional[Any] = None
    user_context: Optional[str] = None
    source_origin: Optional[str] = None


@dataclass
class GetCookiesParameters:
    """GetCookiesParameters type type."""

    filter: Optional[Any] = None
    partition: Optional[Any] = None


@dataclass
class GetCookiesResult:
    """GetCookiesResult type type."""

    cookies: Optional[List[Optional[Any]]] = field(default_factory=list)
    partition_key: Optional[Any] = None


@dataclass
class PartialCookie:
    """PartialCookie type type."""

    name: Optional[str] = None
    value: Optional[Any] = None
    domain: Optional[str] = None
    path: Optional[str] = None
    http_only: Optional[bool] = None
    secure: Optional[bool] = None
    same_site: Optional[Any] = None
    expiry: Optional[Any] = None


@dataclass
class SetCookieParameters:
    """SetCookieParameters type type."""

    cookie: Optional[Any] = None
    partition: Optional[Any] = None


@dataclass
class SetCookieResult:
    """SetCookieResult type type."""

    partition_key: Optional[Any] = None


@dataclass
class DeleteCookiesParameters:
    """DeleteCookiesParameters type type."""

    filter: Optional[Any] = None
    partition: Optional[Any] = None


@dataclass
class DeleteCookiesResult:
    """DeleteCookiesResult type type."""

    partition_key: Optional[Any] = None


class Storage:
    """WebDriver BiDi storage module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def get_cookies(self, filter: Any = None, partition: Any = None) -> Generator[dict, dict, dict]:
        """Execute storage.getCookies."""
        params = {
            "filter": filter,
            "partition": partition,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("storage.getCookies", params)

    def set_cookie(self, cookie: Any = None, partition: Any = None) -> Generator[dict, dict, dict]:
        """Execute storage.setCookie."""
        params = {
            "cookie": cookie,
            "partition": partition,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("storage.setCookie", params)

    def delete_cookies(self, filter: Any = None, partition: Any = None) -> Generator[dict, dict, dict]:
        """Execute storage.deleteCookies."""
        params = {
            "filter": filter,
            "partition": partition,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("storage.deleteCookies", params)

