# DO NOT EDIT THIS FILE!
#
# This file is generated from the WebDriver BiDi specification. If you need to make
# changes, edit the generator and regenerate all of the modules.
#
# WebDriver BiDi module: webExtension
from __future__ import annotations

from typing import Any, Dict, List, Optional, Union
from .common import command_builder
from dataclasses import field
from typing import Generator
from dataclasses import dataclass


@dataclass
class InstallParameters:
    """InstallParameters type type."""

    extension_data: Optional[Any] = None


@dataclass
class ExtensionPath:
    """ExtensionPath type type."""

    type: Optional[Any] = None
    path: Optional[str] = None


@dataclass
class ExtensionArchivePath:
    """ExtensionArchivePath type type."""

    type: Optional[Any] = None
    path: Optional[str] = None


@dataclass
class ExtensionBase64Encoded:
    """ExtensionBase64Encoded type type."""

    type: Optional[Any] = None
    value: Optional[str] = None


@dataclass
class InstallResult:
    """InstallResult type type."""

    extension: Optional[Any] = None


@dataclass
class UninstallParameters:
    """UninstallParameters type type."""

    extension: Optional[Any] = None


class WebExtension:
    """WebDriver BiDi webExtension module."""

    def __init__(self, driver) -> None:
        self._driver = driver

    def install(self, extension_data: Any = None) -> Generator[dict, dict, dict]:
        """Execute webExtension.install."""
        params = {
            "extensionData": extension_data,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("webExtension.install", params)

    def uninstall(self, extension: Any = None) -> Generator[dict, dict, dict]:
        """Execute webExtension.uninstall."""
        params = {
            "extension": extension,
        }
        params = {k: v for k, v in params.items() if v is not None}
        return command_builder("webExtension.uninstall", params)

